// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gosync/internal/models"
)

func newDevice(db *gorm.DB, opts ...gen.DOOption) device {
	_device := device{}

	_device.deviceDo.UseDB(db, opts...)
	_device.deviceDo.UseModel(&models.Device{})

	tableName := _device.deviceDo.TableName()
	_device.ALL = field.NewAsterisk(tableName)
	_device.ID = field.NewField(tableName, "id")
	_device.UserID = field.NewField(tableName, "user_id")
	_device.Name = field.NewString(tableName, "name")
	_device.LastSyncAt = field.NewTime(tableName, "last_sync_at")
	_device.LastRootHash = field.NewString(tableName, "last_root_hash")
	_device.CreatedAt = field.NewTime(tableName, "created_at")
	_device.User = deviceBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "models.User"),
		RootDirectory: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Parent struct {
				field.RelationField
			}
			Children struct {
				field.RelationField
			}
			Files struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Directory struct {
					field.RelationField
				}
				CurrentVersion struct {
					field.RelationField
					File struct {
						field.RelationField
					}
				}
				Versions struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("User.RootDirectory", "models.Directory"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.RootDirectory.User", "models.User"),
			},
			Parent: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.RootDirectory.Parent", "models.Directory"),
			},
			Children: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.RootDirectory.Children", "models.Directory"),
			},
			Files: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Directory struct {
					field.RelationField
				}
				CurrentVersion struct {
					field.RelationField
					File struct {
						field.RelationField
					}
				}
				Versions struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("User.RootDirectory.Files", "models.File"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.RootDirectory.Files.User", "models.User"),
				},
				Directory: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.RootDirectory.Files.Directory", "models.Directory"),
				},
				CurrentVersion: struct {
					field.RelationField
					File struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("User.RootDirectory.Files.CurrentVersion", "models.FileVersion"),
					File: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("User.RootDirectory.Files.CurrentVersion.File", "models.File"),
					},
				},
				Versions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.RootDirectory.Files.Versions", "models.FileVersion"),
				},
			},
		},
		Devices: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.Devices", "models.Device"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Devices.User", "models.User"),
			},
		},
		Directories: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.Directories", "models.Directory"),
		},
		Files: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.Files", "models.File"),
		},
		Events: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			File struct {
				field.RelationField
			}
			Directory struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.Events", "models.Event"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Events.User", "models.User"),
			},
			File: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Events.File", "models.File"),
			},
			Directory: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Events.Directory", "models.Directory"),
			},
		},
	}

	_device.fillFieldMap()

	return _device
}

type device struct {
	deviceDo deviceDo

	ALL          field.Asterisk
	ID           field.Field
	UserID       field.Field
	Name         field.String
	LastSyncAt   field.Time
	LastRootHash field.String
	CreatedAt    field.Time
	User         deviceBelongsToUser

	fieldMap map[string]field.Expr
}

func (d device) Table(newTableName string) *device {
	d.deviceDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d device) As(alias string) *device {
	d.deviceDo.DO = *(d.deviceDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *device) updateTableName(table string) *device {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewField(table, "id")
	d.UserID = field.NewField(table, "user_id")
	d.Name = field.NewString(table, "name")
	d.LastSyncAt = field.NewTime(table, "last_sync_at")
	d.LastRootHash = field.NewString(table, "last_root_hash")
	d.CreatedAt = field.NewTime(table, "created_at")

	d.fillFieldMap()

	return d
}

func (d *device) WithContext(ctx context.Context) IDeviceDo { return d.deviceDo.WithContext(ctx) }

func (d device) TableName() string { return d.deviceDo.TableName() }

func (d device) Alias() string { return d.deviceDo.Alias() }

func (d device) Columns(cols ...field.Expr) gen.Columns { return d.deviceDo.Columns(cols...) }

func (d *device) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *device) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 7)
	d.fieldMap["id"] = d.ID
	d.fieldMap["user_id"] = d.UserID
	d.fieldMap["name"] = d.Name
	d.fieldMap["last_sync_at"] = d.LastSyncAt
	d.fieldMap["last_root_hash"] = d.LastRootHash
	d.fieldMap["created_at"] = d.CreatedAt

}

func (d device) clone(db *gorm.DB) device {
	d.deviceDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d device) replaceDB(db *gorm.DB) device {
	d.deviceDo.ReplaceDB(db)
	return d
}

type deviceBelongsToUser struct {
	db *gorm.DB

	field.RelationField

	RootDirectory struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		Parent struct {
			field.RelationField
		}
		Children struct {
			field.RelationField
		}
		Files struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Directory struct {
				field.RelationField
			}
			CurrentVersion struct {
				field.RelationField
				File struct {
					field.RelationField
				}
			}
			Versions struct {
				field.RelationField
			}
		}
	}
	Devices struct {
		field.RelationField
		User struct {
			field.RelationField
		}
	}
	Directories struct {
		field.RelationField
	}
	Files struct {
		field.RelationField
	}
	Events struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		File struct {
			field.RelationField
		}
		Directory struct {
			field.RelationField
		}
	}
}

func (a deviceBelongsToUser) Where(conds ...field.Expr) *deviceBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a deviceBelongsToUser) WithContext(ctx context.Context) *deviceBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a deviceBelongsToUser) Session(session *gorm.Session) *deviceBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a deviceBelongsToUser) Model(m *models.Device) *deviceBelongsToUserTx {
	return &deviceBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

type deviceBelongsToUserTx struct{ tx *gorm.Association }

func (a deviceBelongsToUserTx) Find() (result *models.User, err error) {
	return result, a.tx.Find(&result)
}

func (a deviceBelongsToUserTx) Append(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a deviceBelongsToUserTx) Replace(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a deviceBelongsToUserTx) Delete(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a deviceBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a deviceBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

type deviceDo struct{ gen.DO }

type IDeviceDo interface {
	gen.SubQuery
	Debug() IDeviceDo
	WithContext(ctx context.Context) IDeviceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeviceDo
	WriteDB() IDeviceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeviceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeviceDo
	Not(conds ...gen.Condition) IDeviceDo
	Or(conds ...gen.Condition) IDeviceDo
	Select(conds ...field.Expr) IDeviceDo
	Where(conds ...gen.Condition) IDeviceDo
	Order(conds ...field.Expr) IDeviceDo
	Distinct(cols ...field.Expr) IDeviceDo
	Omit(cols ...field.Expr) IDeviceDo
	Join(table schema.Tabler, on ...field.Expr) IDeviceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeviceDo
	Group(cols ...field.Expr) IDeviceDo
	Having(conds ...gen.Condition) IDeviceDo
	Limit(limit int) IDeviceDo
	Offset(offset int) IDeviceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceDo
	Unscoped() IDeviceDo
	Create(values ...*models.Device) error
	CreateInBatches(values []*models.Device, batchSize int) error
	Save(values ...*models.Device) error
	First() (*models.Device, error)
	Take() (*models.Device, error)
	Last() (*models.Device, error)
	Find() ([]*models.Device, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Device, err error)
	FindInBatches(result *[]*models.Device, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Device) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeviceDo
	Assign(attrs ...field.AssignExpr) IDeviceDo
	Joins(fields ...field.RelationField) IDeviceDo
	Preload(fields ...field.RelationField) IDeviceDo
	FirstOrInit() (*models.Device, error)
	FirstOrCreate() (*models.Device, error)
	FindByPage(offset int, limit int) (result []*models.Device, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeviceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deviceDo) Debug() IDeviceDo {
	return d.withDO(d.DO.Debug())
}

func (d deviceDo) WithContext(ctx context.Context) IDeviceDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deviceDo) ReadDB() IDeviceDo {
	return d.Clauses(dbresolver.Read)
}

func (d deviceDo) WriteDB() IDeviceDo {
	return d.Clauses(dbresolver.Write)
}

func (d deviceDo) Session(config *gorm.Session) IDeviceDo {
	return d.withDO(d.DO.Session(config))
}

func (d deviceDo) Clauses(conds ...clause.Expression) IDeviceDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deviceDo) Returning(value interface{}, columns ...string) IDeviceDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deviceDo) Not(conds ...gen.Condition) IDeviceDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deviceDo) Or(conds ...gen.Condition) IDeviceDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deviceDo) Select(conds ...field.Expr) IDeviceDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deviceDo) Where(conds ...gen.Condition) IDeviceDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deviceDo) Order(conds ...field.Expr) IDeviceDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deviceDo) Distinct(cols ...field.Expr) IDeviceDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deviceDo) Omit(cols ...field.Expr) IDeviceDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deviceDo) Join(table schema.Tabler, on ...field.Expr) IDeviceDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deviceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deviceDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeviceDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deviceDo) Group(cols ...field.Expr) IDeviceDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deviceDo) Having(conds ...gen.Condition) IDeviceDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deviceDo) Limit(limit int) IDeviceDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deviceDo) Offset(offset int) IDeviceDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deviceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deviceDo) Unscoped() IDeviceDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deviceDo) Create(values ...*models.Device) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deviceDo) CreateInBatches(values []*models.Device, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deviceDo) Save(values ...*models.Device) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deviceDo) First() (*models.Device, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Device), nil
	}
}

func (d deviceDo) Take() (*models.Device, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Device), nil
	}
}

func (d deviceDo) Last() (*models.Device, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Device), nil
	}
}

func (d deviceDo) Find() ([]*models.Device, error) {
	result, err := d.DO.Find()
	return result.([]*models.Device), err
}

func (d deviceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Device, err error) {
	buf := make([]*models.Device, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deviceDo) FindInBatches(result *[]*models.Device, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deviceDo) Attrs(attrs ...field.AssignExpr) IDeviceDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deviceDo) Assign(attrs ...field.AssignExpr) IDeviceDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deviceDo) Joins(fields ...field.RelationField) IDeviceDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deviceDo) Preload(fields ...field.RelationField) IDeviceDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deviceDo) FirstOrInit() (*models.Device, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Device), nil
	}
}

func (d deviceDo) FirstOrCreate() (*models.Device, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Device), nil
	}
}

func (d deviceDo) FindByPage(offset int, limit int) (result []*models.Device, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deviceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deviceDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deviceDo) Delete(models ...*models.Device) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deviceDo) withDO(do gen.Dao) *deviceDo {
	d.DO = *do.(*gen.DO)
	return d
}
