// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gosync/internal/models"
)

func newDirectory(db *gorm.DB, opts ...gen.DOOption) directory {
	_directory := directory{}

	_directory.directoryDo.UseDB(db, opts...)
	_directory.directoryDo.UseModel(&models.Directory{})

	tableName := _directory.directoryDo.TableName()
	_directory.ALL = field.NewAsterisk(tableName)
	_directory.ID = field.NewField(tableName, "id")
	_directory.UserID = field.NewField(tableName, "user_id")
	_directory.ParentID = field.NewField(tableName, "parent_id")
	_directory.Name = field.NewString(tableName, "name")
	_directory.MerkleHash = field.NewString(tableName, "merkle_hash")
	_directory.CreatedAt = field.NewTime(tableName, "created_at")
	_directory.UpdatedAt = field.NewTime(tableName, "updated_at")
	_directory.DeletedAt = field.NewTime(tableName, "deleted_at")
	_directory.Children = directoryHasManyChildren{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Children", "models.Directory"),
		User: struct {
			field.RelationField
			Devices struct {
				field.RelationField
				User struct {
					field.RelationField
				}
			}
			Directories struct {
				field.RelationField
			}
			Files struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Directory struct {
					field.RelationField
				}
				CurrentVersion struct {
					field.RelationField
					File struct {
						field.RelationField
					}
				}
				Versions struct {
					field.RelationField
				}
			}
			Events struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Device struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Children.User", "models.User"),
			Devices: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Children.User.Devices", "models.Device"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Children.User.Devices.User", "models.User"),
				},
			},
			Directories: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Children.User.Directories", "models.Directory"),
			},
			Files: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Directory struct {
					field.RelationField
				}
				CurrentVersion struct {
					field.RelationField
					File struct {
						field.RelationField
					}
				}
				Versions struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Children.User.Files", "models.File"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Children.User.Files.User", "models.User"),
				},
				Directory: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Children.User.Files.Directory", "models.Directory"),
				},
				CurrentVersion: struct {
					field.RelationField
					File struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Children.User.Files.CurrentVersion", "models.FileVersion"),
					File: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Children.User.Files.CurrentVersion.File", "models.File"),
					},
				},
				Versions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Children.User.Files.Versions", "models.FileVersion"),
				},
			},
			Events: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Device struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Children.User.Events", "models.SyncEvent"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Children.User.Events.User", "models.User"),
				},
				Device: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Children.User.Events.Device", "models.Device"),
				},
			},
		},
		Parent: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Children.Parent", "models.Directory"),
		},
		Children: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Children.Children", "models.Directory"),
		},
		Files: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Children.Files", "models.File"),
		},
	}

	_directory.Files = directoryHasManyFiles{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Files", "models.File"),
	}

	_directory.User = directoryBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "models.User"),
	}

	_directory.Parent = directoryBelongsToParent{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Parent", "models.Directory"),
	}

	_directory.fillFieldMap()

	return _directory
}

type directory struct {
	directoryDo directoryDo

	ALL        field.Asterisk
	ID         field.Field
	UserID     field.Field
	ParentID   field.Field
	Name       field.String
	MerkleHash field.String
	CreatedAt  field.Time
	UpdatedAt  field.Time
	DeletedAt  field.Time
	Children   directoryHasManyChildren

	Files directoryHasManyFiles

	User directoryBelongsToUser

	Parent directoryBelongsToParent

	fieldMap map[string]field.Expr
}

func (d directory) Table(newTableName string) *directory {
	d.directoryDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d directory) As(alias string) *directory {
	d.directoryDo.DO = *(d.directoryDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *directory) updateTableName(table string) *directory {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewField(table, "id")
	d.UserID = field.NewField(table, "user_id")
	d.ParentID = field.NewField(table, "parent_id")
	d.Name = field.NewString(table, "name")
	d.MerkleHash = field.NewString(table, "merkle_hash")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")
	d.DeletedAt = field.NewTime(table, "deleted_at")

	d.fillFieldMap()

	return d
}

func (d *directory) WithContext(ctx context.Context) IDirectoryDo {
	return d.directoryDo.WithContext(ctx)
}

func (d directory) TableName() string { return d.directoryDo.TableName() }

func (d directory) Alias() string { return d.directoryDo.Alias() }

func (d directory) Columns(cols ...field.Expr) gen.Columns { return d.directoryDo.Columns(cols...) }

func (d *directory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *directory) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 12)
	d.fieldMap["id"] = d.ID
	d.fieldMap["user_id"] = d.UserID
	d.fieldMap["parent_id"] = d.ParentID
	d.fieldMap["name"] = d.Name
	d.fieldMap["merkle_hash"] = d.MerkleHash
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
	d.fieldMap["deleted_at"] = d.DeletedAt

}

func (d directory) clone(db *gorm.DB) directory {
	d.directoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d directory) replaceDB(db *gorm.DB) directory {
	d.directoryDo.ReplaceDB(db)
	return d
}

type directoryHasManyChildren struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
		Devices struct {
			field.RelationField
			User struct {
				field.RelationField
			}
		}
		Directories struct {
			field.RelationField
		}
		Files struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Directory struct {
				field.RelationField
			}
			CurrentVersion struct {
				field.RelationField
				File struct {
					field.RelationField
				}
			}
			Versions struct {
				field.RelationField
			}
		}
		Events struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Device struct {
				field.RelationField
			}
		}
	}
	Parent struct {
		field.RelationField
	}
	Children struct {
		field.RelationField
	}
	Files struct {
		field.RelationField
	}
}

func (a directoryHasManyChildren) Where(conds ...field.Expr) *directoryHasManyChildren {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a directoryHasManyChildren) WithContext(ctx context.Context) *directoryHasManyChildren {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a directoryHasManyChildren) Session(session *gorm.Session) *directoryHasManyChildren {
	a.db = a.db.Session(session)
	return &a
}

func (a directoryHasManyChildren) Model(m *models.Directory) *directoryHasManyChildrenTx {
	return &directoryHasManyChildrenTx{a.db.Model(m).Association(a.Name())}
}

type directoryHasManyChildrenTx struct{ tx *gorm.Association }

func (a directoryHasManyChildrenTx) Find() (result []*models.Directory, err error) {
	return result, a.tx.Find(&result)
}

func (a directoryHasManyChildrenTx) Append(values ...*models.Directory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a directoryHasManyChildrenTx) Replace(values ...*models.Directory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a directoryHasManyChildrenTx) Delete(values ...*models.Directory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a directoryHasManyChildrenTx) Clear() error {
	return a.tx.Clear()
}

func (a directoryHasManyChildrenTx) Count() int64 {
	return a.tx.Count()
}

type directoryHasManyFiles struct {
	db *gorm.DB

	field.RelationField
}

func (a directoryHasManyFiles) Where(conds ...field.Expr) *directoryHasManyFiles {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a directoryHasManyFiles) WithContext(ctx context.Context) *directoryHasManyFiles {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a directoryHasManyFiles) Session(session *gorm.Session) *directoryHasManyFiles {
	a.db = a.db.Session(session)
	return &a
}

func (a directoryHasManyFiles) Model(m *models.Directory) *directoryHasManyFilesTx {
	return &directoryHasManyFilesTx{a.db.Model(m).Association(a.Name())}
}

type directoryHasManyFilesTx struct{ tx *gorm.Association }

func (a directoryHasManyFilesTx) Find() (result []*models.File, err error) {
	return result, a.tx.Find(&result)
}

func (a directoryHasManyFilesTx) Append(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a directoryHasManyFilesTx) Replace(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a directoryHasManyFilesTx) Delete(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a directoryHasManyFilesTx) Clear() error {
	return a.tx.Clear()
}

func (a directoryHasManyFilesTx) Count() int64 {
	return a.tx.Count()
}

type directoryBelongsToUser struct {
	db *gorm.DB

	field.RelationField
}

func (a directoryBelongsToUser) Where(conds ...field.Expr) *directoryBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a directoryBelongsToUser) WithContext(ctx context.Context) *directoryBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a directoryBelongsToUser) Session(session *gorm.Session) *directoryBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a directoryBelongsToUser) Model(m *models.Directory) *directoryBelongsToUserTx {
	return &directoryBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

type directoryBelongsToUserTx struct{ tx *gorm.Association }

func (a directoryBelongsToUserTx) Find() (result *models.User, err error) {
	return result, a.tx.Find(&result)
}

func (a directoryBelongsToUserTx) Append(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a directoryBelongsToUserTx) Replace(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a directoryBelongsToUserTx) Delete(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a directoryBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a directoryBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

type directoryBelongsToParent struct {
	db *gorm.DB

	field.RelationField
}

func (a directoryBelongsToParent) Where(conds ...field.Expr) *directoryBelongsToParent {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a directoryBelongsToParent) WithContext(ctx context.Context) *directoryBelongsToParent {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a directoryBelongsToParent) Session(session *gorm.Session) *directoryBelongsToParent {
	a.db = a.db.Session(session)
	return &a
}

func (a directoryBelongsToParent) Model(m *models.Directory) *directoryBelongsToParentTx {
	return &directoryBelongsToParentTx{a.db.Model(m).Association(a.Name())}
}

type directoryBelongsToParentTx struct{ tx *gorm.Association }

func (a directoryBelongsToParentTx) Find() (result *models.Directory, err error) {
	return result, a.tx.Find(&result)
}

func (a directoryBelongsToParentTx) Append(values ...*models.Directory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a directoryBelongsToParentTx) Replace(values ...*models.Directory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a directoryBelongsToParentTx) Delete(values ...*models.Directory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a directoryBelongsToParentTx) Clear() error {
	return a.tx.Clear()
}

func (a directoryBelongsToParentTx) Count() int64 {
	return a.tx.Count()
}

type directoryDo struct{ gen.DO }

type IDirectoryDo interface {
	gen.SubQuery
	Debug() IDirectoryDo
	WithContext(ctx context.Context) IDirectoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDirectoryDo
	WriteDB() IDirectoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDirectoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDirectoryDo
	Not(conds ...gen.Condition) IDirectoryDo
	Or(conds ...gen.Condition) IDirectoryDo
	Select(conds ...field.Expr) IDirectoryDo
	Where(conds ...gen.Condition) IDirectoryDo
	Order(conds ...field.Expr) IDirectoryDo
	Distinct(cols ...field.Expr) IDirectoryDo
	Omit(cols ...field.Expr) IDirectoryDo
	Join(table schema.Tabler, on ...field.Expr) IDirectoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDirectoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDirectoryDo
	Group(cols ...field.Expr) IDirectoryDo
	Having(conds ...gen.Condition) IDirectoryDo
	Limit(limit int) IDirectoryDo
	Offset(offset int) IDirectoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDirectoryDo
	Unscoped() IDirectoryDo
	Create(values ...*models.Directory) error
	CreateInBatches(values []*models.Directory, batchSize int) error
	Save(values ...*models.Directory) error
	First() (*models.Directory, error)
	Take() (*models.Directory, error)
	Last() (*models.Directory, error)
	Find() ([]*models.Directory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Directory, err error)
	FindInBatches(result *[]*models.Directory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Directory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDirectoryDo
	Assign(attrs ...field.AssignExpr) IDirectoryDo
	Joins(fields ...field.RelationField) IDirectoryDo
	Preload(fields ...field.RelationField) IDirectoryDo
	FirstOrInit() (*models.Directory, error)
	FirstOrCreate() (*models.Directory, error)
	FindByPage(offset int, limit int) (result []*models.Directory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDirectoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d directoryDo) Debug() IDirectoryDo {
	return d.withDO(d.DO.Debug())
}

func (d directoryDo) WithContext(ctx context.Context) IDirectoryDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d directoryDo) ReadDB() IDirectoryDo {
	return d.Clauses(dbresolver.Read)
}

func (d directoryDo) WriteDB() IDirectoryDo {
	return d.Clauses(dbresolver.Write)
}

func (d directoryDo) Session(config *gorm.Session) IDirectoryDo {
	return d.withDO(d.DO.Session(config))
}

func (d directoryDo) Clauses(conds ...clause.Expression) IDirectoryDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d directoryDo) Returning(value interface{}, columns ...string) IDirectoryDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d directoryDo) Not(conds ...gen.Condition) IDirectoryDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d directoryDo) Or(conds ...gen.Condition) IDirectoryDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d directoryDo) Select(conds ...field.Expr) IDirectoryDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d directoryDo) Where(conds ...gen.Condition) IDirectoryDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d directoryDo) Order(conds ...field.Expr) IDirectoryDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d directoryDo) Distinct(cols ...field.Expr) IDirectoryDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d directoryDo) Omit(cols ...field.Expr) IDirectoryDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d directoryDo) Join(table schema.Tabler, on ...field.Expr) IDirectoryDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d directoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDirectoryDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d directoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IDirectoryDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d directoryDo) Group(cols ...field.Expr) IDirectoryDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d directoryDo) Having(conds ...gen.Condition) IDirectoryDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d directoryDo) Limit(limit int) IDirectoryDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d directoryDo) Offset(offset int) IDirectoryDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d directoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDirectoryDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d directoryDo) Unscoped() IDirectoryDo {
	return d.withDO(d.DO.Unscoped())
}

func (d directoryDo) Create(values ...*models.Directory) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d directoryDo) CreateInBatches(values []*models.Directory, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d directoryDo) Save(values ...*models.Directory) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d directoryDo) First() (*models.Directory, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Directory), nil
	}
}

func (d directoryDo) Take() (*models.Directory, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Directory), nil
	}
}

func (d directoryDo) Last() (*models.Directory, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Directory), nil
	}
}

func (d directoryDo) Find() ([]*models.Directory, error) {
	result, err := d.DO.Find()
	return result.([]*models.Directory), err
}

func (d directoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Directory, err error) {
	buf := make([]*models.Directory, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d directoryDo) FindInBatches(result *[]*models.Directory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d directoryDo) Attrs(attrs ...field.AssignExpr) IDirectoryDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d directoryDo) Assign(attrs ...field.AssignExpr) IDirectoryDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d directoryDo) Joins(fields ...field.RelationField) IDirectoryDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d directoryDo) Preload(fields ...field.RelationField) IDirectoryDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d directoryDo) FirstOrInit() (*models.Directory, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Directory), nil
	}
}

func (d directoryDo) FirstOrCreate() (*models.Directory, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Directory), nil
	}
}

func (d directoryDo) FindByPage(offset int, limit int) (result []*models.Directory, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d directoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d directoryDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d directoryDo) Delete(models ...*models.Directory) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *directoryDo) withDO(do gen.Dao) *directoryDo {
	d.DO = *do.(*gen.DO)
	return d
}
