// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gosync/internal/models"
)

func newEvent(db *gorm.DB, opts ...gen.DOOption) event {
	_event := event{}

	_event.eventDo.UseDB(db, opts...)
	_event.eventDo.UseModel(&models.Event{})

	tableName := _event.eventDo.TableName()
	_event.ALL = field.NewAsterisk(tableName)
	_event.ID = field.NewUint64(tableName, "id")
	_event.UserID = field.NewField(tableName, "user_id")
	_event.Type = field.NewString(tableName, "type")
	_event.FileID = field.NewField(tableName, "file_id")
	_event.DirectoryID = field.NewField(tableName, "directory_id")
	_event.CreatedAt = field.NewTime(tableName, "created_at")
	_event.User = eventBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "models.User"),
		RootDirectory: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Parent struct {
				field.RelationField
			}
			Children struct {
				field.RelationField
			}
			Files struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Directory struct {
					field.RelationField
				}
				CurrentVersion struct {
					field.RelationField
					File struct {
						field.RelationField
					}
				}
				Versions struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("User.RootDirectory", "models.Directory"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.RootDirectory.User", "models.User"),
			},
			Parent: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.RootDirectory.Parent", "models.Directory"),
			},
			Children: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.RootDirectory.Children", "models.Directory"),
			},
			Files: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Directory struct {
					field.RelationField
				}
				CurrentVersion struct {
					field.RelationField
					File struct {
						field.RelationField
					}
				}
				Versions struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("User.RootDirectory.Files", "models.File"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.RootDirectory.Files.User", "models.User"),
				},
				Directory: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.RootDirectory.Files.Directory", "models.Directory"),
				},
				CurrentVersion: struct {
					field.RelationField
					File struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("User.RootDirectory.Files.CurrentVersion", "models.FileVersion"),
					File: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("User.RootDirectory.Files.CurrentVersion.File", "models.File"),
					},
				},
				Versions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.RootDirectory.Files.Versions", "models.FileVersion"),
				},
			},
		},
		Devices: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.Devices", "models.Device"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Devices.User", "models.User"),
			},
		},
		Directories: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.Directories", "models.Directory"),
		},
		Files: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.Files", "models.File"),
		},
		Events: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			File struct {
				field.RelationField
			}
			Directory struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.Events", "models.Event"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Events.User", "models.User"),
			},
			File: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Events.File", "models.File"),
			},
			Directory: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Events.Directory", "models.Directory"),
			},
		},
	}

	_event.File = eventBelongsToFile{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("File", "models.File"),
	}

	_event.Directory = eventBelongsToDirectory{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Directory", "models.Directory"),
	}

	_event.fillFieldMap()

	return _event
}

type event struct {
	eventDo eventDo

	ALL         field.Asterisk
	ID          field.Uint64
	UserID      field.Field
	Type        field.String
	FileID      field.Field
	DirectoryID field.Field
	CreatedAt   field.Time
	User        eventBelongsToUser

	File eventBelongsToFile

	Directory eventBelongsToDirectory

	fieldMap map[string]field.Expr
}

func (e event) Table(newTableName string) *event {
	e.eventDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e event) As(alias string) *event {
	e.eventDo.DO = *(e.eventDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *event) updateTableName(table string) *event {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewUint64(table, "id")
	e.UserID = field.NewField(table, "user_id")
	e.Type = field.NewString(table, "type")
	e.FileID = field.NewField(table, "file_id")
	e.DirectoryID = field.NewField(table, "directory_id")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *event) WithContext(ctx context.Context) IEventDo { return e.eventDo.WithContext(ctx) }

func (e event) TableName() string { return e.eventDo.TableName() }

func (e event) Alias() string { return e.eventDo.Alias() }

func (e event) Columns(cols ...field.Expr) gen.Columns { return e.eventDo.Columns(cols...) }

func (e *event) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *event) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 9)
	e.fieldMap["id"] = e.ID
	e.fieldMap["user_id"] = e.UserID
	e.fieldMap["type"] = e.Type
	e.fieldMap["file_id"] = e.FileID
	e.fieldMap["directory_id"] = e.DirectoryID
	e.fieldMap["created_at"] = e.CreatedAt

}

func (e event) clone(db *gorm.DB) event {
	e.eventDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e event) replaceDB(db *gorm.DB) event {
	e.eventDo.ReplaceDB(db)
	return e
}

type eventBelongsToUser struct {
	db *gorm.DB

	field.RelationField

	RootDirectory struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		Parent struct {
			field.RelationField
		}
		Children struct {
			field.RelationField
		}
		Files struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Directory struct {
				field.RelationField
			}
			CurrentVersion struct {
				field.RelationField
				File struct {
					field.RelationField
				}
			}
			Versions struct {
				field.RelationField
			}
		}
	}
	Devices struct {
		field.RelationField
		User struct {
			field.RelationField
		}
	}
	Directories struct {
		field.RelationField
	}
	Files struct {
		field.RelationField
	}
	Events struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		File struct {
			field.RelationField
		}
		Directory struct {
			field.RelationField
		}
	}
}

func (a eventBelongsToUser) Where(conds ...field.Expr) *eventBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a eventBelongsToUser) WithContext(ctx context.Context) *eventBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a eventBelongsToUser) Session(session *gorm.Session) *eventBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a eventBelongsToUser) Model(m *models.Event) *eventBelongsToUserTx {
	return &eventBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

type eventBelongsToUserTx struct{ tx *gorm.Association }

func (a eventBelongsToUserTx) Find() (result *models.User, err error) {
	return result, a.tx.Find(&result)
}

func (a eventBelongsToUserTx) Append(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a eventBelongsToUserTx) Replace(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a eventBelongsToUserTx) Delete(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a eventBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a eventBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

type eventBelongsToFile struct {
	db *gorm.DB

	field.RelationField
}

func (a eventBelongsToFile) Where(conds ...field.Expr) *eventBelongsToFile {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a eventBelongsToFile) WithContext(ctx context.Context) *eventBelongsToFile {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a eventBelongsToFile) Session(session *gorm.Session) *eventBelongsToFile {
	a.db = a.db.Session(session)
	return &a
}

func (a eventBelongsToFile) Model(m *models.Event) *eventBelongsToFileTx {
	return &eventBelongsToFileTx{a.db.Model(m).Association(a.Name())}
}

type eventBelongsToFileTx struct{ tx *gorm.Association }

func (a eventBelongsToFileTx) Find() (result *models.File, err error) {
	return result, a.tx.Find(&result)
}

func (a eventBelongsToFileTx) Append(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a eventBelongsToFileTx) Replace(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a eventBelongsToFileTx) Delete(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a eventBelongsToFileTx) Clear() error {
	return a.tx.Clear()
}

func (a eventBelongsToFileTx) Count() int64 {
	return a.tx.Count()
}

type eventBelongsToDirectory struct {
	db *gorm.DB

	field.RelationField
}

func (a eventBelongsToDirectory) Where(conds ...field.Expr) *eventBelongsToDirectory {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a eventBelongsToDirectory) WithContext(ctx context.Context) *eventBelongsToDirectory {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a eventBelongsToDirectory) Session(session *gorm.Session) *eventBelongsToDirectory {
	a.db = a.db.Session(session)
	return &a
}

func (a eventBelongsToDirectory) Model(m *models.Event) *eventBelongsToDirectoryTx {
	return &eventBelongsToDirectoryTx{a.db.Model(m).Association(a.Name())}
}

type eventBelongsToDirectoryTx struct{ tx *gorm.Association }

func (a eventBelongsToDirectoryTx) Find() (result *models.Directory, err error) {
	return result, a.tx.Find(&result)
}

func (a eventBelongsToDirectoryTx) Append(values ...*models.Directory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a eventBelongsToDirectoryTx) Replace(values ...*models.Directory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a eventBelongsToDirectoryTx) Delete(values ...*models.Directory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a eventBelongsToDirectoryTx) Clear() error {
	return a.tx.Clear()
}

func (a eventBelongsToDirectoryTx) Count() int64 {
	return a.tx.Count()
}

type eventDo struct{ gen.DO }

type IEventDo interface {
	gen.SubQuery
	Debug() IEventDo
	WithContext(ctx context.Context) IEventDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEventDo
	WriteDB() IEventDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEventDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEventDo
	Not(conds ...gen.Condition) IEventDo
	Or(conds ...gen.Condition) IEventDo
	Select(conds ...field.Expr) IEventDo
	Where(conds ...gen.Condition) IEventDo
	Order(conds ...field.Expr) IEventDo
	Distinct(cols ...field.Expr) IEventDo
	Omit(cols ...field.Expr) IEventDo
	Join(table schema.Tabler, on ...field.Expr) IEventDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEventDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEventDo
	Group(cols ...field.Expr) IEventDo
	Having(conds ...gen.Condition) IEventDo
	Limit(limit int) IEventDo
	Offset(offset int) IEventDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEventDo
	Unscoped() IEventDo
	Create(values ...*models.Event) error
	CreateInBatches(values []*models.Event, batchSize int) error
	Save(values ...*models.Event) error
	First() (*models.Event, error)
	Take() (*models.Event, error)
	Last() (*models.Event, error)
	Find() ([]*models.Event, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Event, err error)
	FindInBatches(result *[]*models.Event, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Event) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEventDo
	Assign(attrs ...field.AssignExpr) IEventDo
	Joins(fields ...field.RelationField) IEventDo
	Preload(fields ...field.RelationField) IEventDo
	FirstOrInit() (*models.Event, error)
	FirstOrCreate() (*models.Event, error)
	FindByPage(offset int, limit int) (result []*models.Event, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEventDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e eventDo) Debug() IEventDo {
	return e.withDO(e.DO.Debug())
}

func (e eventDo) WithContext(ctx context.Context) IEventDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventDo) ReadDB() IEventDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventDo) WriteDB() IEventDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventDo) Session(config *gorm.Session) IEventDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventDo) Clauses(conds ...clause.Expression) IEventDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventDo) Returning(value interface{}, columns ...string) IEventDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventDo) Not(conds ...gen.Condition) IEventDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventDo) Or(conds ...gen.Condition) IEventDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventDo) Select(conds ...field.Expr) IEventDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventDo) Where(conds ...gen.Condition) IEventDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventDo) Order(conds ...field.Expr) IEventDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventDo) Distinct(cols ...field.Expr) IEventDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventDo) Omit(cols ...field.Expr) IEventDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventDo) Join(table schema.Tabler, on ...field.Expr) IEventDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEventDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventDo) RightJoin(table schema.Tabler, on ...field.Expr) IEventDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventDo) Group(cols ...field.Expr) IEventDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventDo) Having(conds ...gen.Condition) IEventDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventDo) Limit(limit int) IEventDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventDo) Offset(offset int) IEventDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEventDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventDo) Unscoped() IEventDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventDo) Create(values ...*models.Event) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventDo) CreateInBatches(values []*models.Event, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventDo) Save(values ...*models.Event) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventDo) First() (*models.Event, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Event), nil
	}
}

func (e eventDo) Take() (*models.Event, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Event), nil
	}
}

func (e eventDo) Last() (*models.Event, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Event), nil
	}
}

func (e eventDo) Find() ([]*models.Event, error) {
	result, err := e.DO.Find()
	return result.([]*models.Event), err
}

func (e eventDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Event, err error) {
	buf := make([]*models.Event, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventDo) FindInBatches(result *[]*models.Event, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventDo) Attrs(attrs ...field.AssignExpr) IEventDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventDo) Assign(attrs ...field.AssignExpr) IEventDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventDo) Joins(fields ...field.RelationField) IEventDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventDo) Preload(fields ...field.RelationField) IEventDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventDo) FirstOrInit() (*models.Event, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Event), nil
	}
}

func (e eventDo) FirstOrCreate() (*models.Event, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Event), nil
	}
}

func (e eventDo) FindByPage(offset int, limit int) (result []*models.Event, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventDo) Delete(models ...*models.Event) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventDo) withDO(do gen.Dao) *eventDo {
	e.DO = *do.(*gen.DO)
	return e
}
