// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gosync/internal/models"
)

func newFileVersion(db *gorm.DB, opts ...gen.DOOption) fileVersion {
	_fileVersion := fileVersion{}

	_fileVersion.fileVersionDo.UseDB(db, opts...)
	_fileVersion.fileVersionDo.UseModel(&models.FileVersion{})

	tableName := _fileVersion.fileVersionDo.TableName()
	_fileVersion.ALL = field.NewAsterisk(tableName)
	_fileVersion.ID = field.NewField(tableName, "id")
	_fileVersion.FileID = field.NewField(tableName, "file_id")
	_fileVersion.VersionNumber = field.NewInt(tableName, "version_number")
	_fileVersion.StorageKey = field.NewString(tableName, "storage_key")
	_fileVersion.SizeBytes = field.NewInt64(tableName, "size_bytes")
	_fileVersion.ContentHash = field.NewString(tableName, "content_hash")
	_fileVersion.CreatedAt = field.NewTime(tableName, "created_at")
	_fileVersion.File = fileVersionBelongsToFile{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("File", "models.File"),
		User: struct {
			field.RelationField
			Devices struct {
				field.RelationField
				User struct {
					field.RelationField
				}
			}
			Directories struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Parent struct {
					field.RelationField
				}
				Children struct {
					field.RelationField
				}
				Files struct {
					field.RelationField
				}
			}
			Files struct {
				field.RelationField
			}
			Events struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Device struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("File.User", "models.User"),
			Devices: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("File.User.Devices", "models.Device"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("File.User.Devices.User", "models.User"),
				},
			},
			Directories: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Parent struct {
					field.RelationField
				}
				Children struct {
					field.RelationField
				}
				Files struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("File.User.Directories", "models.Directory"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("File.User.Directories.User", "models.User"),
				},
				Parent: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("File.User.Directories.Parent", "models.Directory"),
				},
				Children: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("File.User.Directories.Children", "models.Directory"),
				},
				Files: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("File.User.Directories.Files", "models.File"),
				},
			},
			Files: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("File.User.Files", "models.File"),
			},
			Events: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Device struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("File.User.Events", "models.SyncEvent"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("File.User.Events.User", "models.User"),
				},
				Device: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("File.User.Events.Device", "models.Device"),
				},
			},
		},
		Directory: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("File.Directory", "models.Directory"),
		},
		CurrentVersion: struct {
			field.RelationField
			File struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("File.CurrentVersion", "models.FileVersion"),
			File: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("File.CurrentVersion.File", "models.File"),
			},
		},
		Versions: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("File.Versions", "models.FileVersion"),
		},
	}

	_fileVersion.fillFieldMap()

	return _fileVersion
}

type fileVersion struct {
	fileVersionDo fileVersionDo

	ALL           field.Asterisk
	ID            field.Field
	FileID        field.Field
	VersionNumber field.Int
	StorageKey    field.String
	SizeBytes     field.Int64
	ContentHash   field.String
	CreatedAt     field.Time
	File          fileVersionBelongsToFile

	fieldMap map[string]field.Expr
}

func (f fileVersion) Table(newTableName string) *fileVersion {
	f.fileVersionDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fileVersion) As(alias string) *fileVersion {
	f.fileVersionDo.DO = *(f.fileVersionDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fileVersion) updateTableName(table string) *fileVersion {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewField(table, "id")
	f.FileID = field.NewField(table, "file_id")
	f.VersionNumber = field.NewInt(table, "version_number")
	f.StorageKey = field.NewString(table, "storage_key")
	f.SizeBytes = field.NewInt64(table, "size_bytes")
	f.ContentHash = field.NewString(table, "content_hash")
	f.CreatedAt = field.NewTime(table, "created_at")

	f.fillFieldMap()

	return f
}

func (f *fileVersion) WithContext(ctx context.Context) IFileVersionDo {
	return f.fileVersionDo.WithContext(ctx)
}

func (f fileVersion) TableName() string { return f.fileVersionDo.TableName() }

func (f fileVersion) Alias() string { return f.fileVersionDo.Alias() }

func (f fileVersion) Columns(cols ...field.Expr) gen.Columns { return f.fileVersionDo.Columns(cols...) }

func (f *fileVersion) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fileVersion) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 8)
	f.fieldMap["id"] = f.ID
	f.fieldMap["file_id"] = f.FileID
	f.fieldMap["version_number"] = f.VersionNumber
	f.fieldMap["storage_key"] = f.StorageKey
	f.fieldMap["size_bytes"] = f.SizeBytes
	f.fieldMap["content_hash"] = f.ContentHash
	f.fieldMap["created_at"] = f.CreatedAt

}

func (f fileVersion) clone(db *gorm.DB) fileVersion {
	f.fileVersionDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fileVersion) replaceDB(db *gorm.DB) fileVersion {
	f.fileVersionDo.ReplaceDB(db)
	return f
}

type fileVersionBelongsToFile struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
		Devices struct {
			field.RelationField
			User struct {
				field.RelationField
			}
		}
		Directories struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Parent struct {
				field.RelationField
			}
			Children struct {
				field.RelationField
			}
			Files struct {
				field.RelationField
			}
		}
		Files struct {
			field.RelationField
		}
		Events struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Device struct {
				field.RelationField
			}
		}
	}
	Directory struct {
		field.RelationField
	}
	CurrentVersion struct {
		field.RelationField
		File struct {
			field.RelationField
		}
	}
	Versions struct {
		field.RelationField
	}
}

func (a fileVersionBelongsToFile) Where(conds ...field.Expr) *fileVersionBelongsToFile {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a fileVersionBelongsToFile) WithContext(ctx context.Context) *fileVersionBelongsToFile {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a fileVersionBelongsToFile) Session(session *gorm.Session) *fileVersionBelongsToFile {
	a.db = a.db.Session(session)
	return &a
}

func (a fileVersionBelongsToFile) Model(m *models.FileVersion) *fileVersionBelongsToFileTx {
	return &fileVersionBelongsToFileTx{a.db.Model(m).Association(a.Name())}
}

type fileVersionBelongsToFileTx struct{ tx *gorm.Association }

func (a fileVersionBelongsToFileTx) Find() (result *models.File, err error) {
	return result, a.tx.Find(&result)
}

func (a fileVersionBelongsToFileTx) Append(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a fileVersionBelongsToFileTx) Replace(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a fileVersionBelongsToFileTx) Delete(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a fileVersionBelongsToFileTx) Clear() error {
	return a.tx.Clear()
}

func (a fileVersionBelongsToFileTx) Count() int64 {
	return a.tx.Count()
}

type fileVersionDo struct{ gen.DO }

type IFileVersionDo interface {
	gen.SubQuery
	Debug() IFileVersionDo
	WithContext(ctx context.Context) IFileVersionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFileVersionDo
	WriteDB() IFileVersionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFileVersionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFileVersionDo
	Not(conds ...gen.Condition) IFileVersionDo
	Or(conds ...gen.Condition) IFileVersionDo
	Select(conds ...field.Expr) IFileVersionDo
	Where(conds ...gen.Condition) IFileVersionDo
	Order(conds ...field.Expr) IFileVersionDo
	Distinct(cols ...field.Expr) IFileVersionDo
	Omit(cols ...field.Expr) IFileVersionDo
	Join(table schema.Tabler, on ...field.Expr) IFileVersionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFileVersionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFileVersionDo
	Group(cols ...field.Expr) IFileVersionDo
	Having(conds ...gen.Condition) IFileVersionDo
	Limit(limit int) IFileVersionDo
	Offset(offset int) IFileVersionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFileVersionDo
	Unscoped() IFileVersionDo
	Create(values ...*models.FileVersion) error
	CreateInBatches(values []*models.FileVersion, batchSize int) error
	Save(values ...*models.FileVersion) error
	First() (*models.FileVersion, error)
	Take() (*models.FileVersion, error)
	Last() (*models.FileVersion, error)
	Find() ([]*models.FileVersion, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.FileVersion, err error)
	FindInBatches(result *[]*models.FileVersion, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.FileVersion) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFileVersionDo
	Assign(attrs ...field.AssignExpr) IFileVersionDo
	Joins(fields ...field.RelationField) IFileVersionDo
	Preload(fields ...field.RelationField) IFileVersionDo
	FirstOrInit() (*models.FileVersion, error)
	FirstOrCreate() (*models.FileVersion, error)
	FindByPage(offset int, limit int) (result []*models.FileVersion, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFileVersionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f fileVersionDo) Debug() IFileVersionDo {
	return f.withDO(f.DO.Debug())
}

func (f fileVersionDo) WithContext(ctx context.Context) IFileVersionDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fileVersionDo) ReadDB() IFileVersionDo {
	return f.Clauses(dbresolver.Read)
}

func (f fileVersionDo) WriteDB() IFileVersionDo {
	return f.Clauses(dbresolver.Write)
}

func (f fileVersionDo) Session(config *gorm.Session) IFileVersionDo {
	return f.withDO(f.DO.Session(config))
}

func (f fileVersionDo) Clauses(conds ...clause.Expression) IFileVersionDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fileVersionDo) Returning(value interface{}, columns ...string) IFileVersionDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fileVersionDo) Not(conds ...gen.Condition) IFileVersionDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fileVersionDo) Or(conds ...gen.Condition) IFileVersionDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fileVersionDo) Select(conds ...field.Expr) IFileVersionDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fileVersionDo) Where(conds ...gen.Condition) IFileVersionDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fileVersionDo) Order(conds ...field.Expr) IFileVersionDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fileVersionDo) Distinct(cols ...field.Expr) IFileVersionDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fileVersionDo) Omit(cols ...field.Expr) IFileVersionDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fileVersionDo) Join(table schema.Tabler, on ...field.Expr) IFileVersionDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fileVersionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFileVersionDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fileVersionDo) RightJoin(table schema.Tabler, on ...field.Expr) IFileVersionDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fileVersionDo) Group(cols ...field.Expr) IFileVersionDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fileVersionDo) Having(conds ...gen.Condition) IFileVersionDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fileVersionDo) Limit(limit int) IFileVersionDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fileVersionDo) Offset(offset int) IFileVersionDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fileVersionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFileVersionDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fileVersionDo) Unscoped() IFileVersionDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fileVersionDo) Create(values ...*models.FileVersion) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fileVersionDo) CreateInBatches(values []*models.FileVersion, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fileVersionDo) Save(values ...*models.FileVersion) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fileVersionDo) First() (*models.FileVersion, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.FileVersion), nil
	}
}

func (f fileVersionDo) Take() (*models.FileVersion, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.FileVersion), nil
	}
}

func (f fileVersionDo) Last() (*models.FileVersion, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.FileVersion), nil
	}
}

func (f fileVersionDo) Find() ([]*models.FileVersion, error) {
	result, err := f.DO.Find()
	return result.([]*models.FileVersion), err
}

func (f fileVersionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.FileVersion, err error) {
	buf := make([]*models.FileVersion, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fileVersionDo) FindInBatches(result *[]*models.FileVersion, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fileVersionDo) Attrs(attrs ...field.AssignExpr) IFileVersionDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fileVersionDo) Assign(attrs ...field.AssignExpr) IFileVersionDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fileVersionDo) Joins(fields ...field.RelationField) IFileVersionDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fileVersionDo) Preload(fields ...field.RelationField) IFileVersionDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fileVersionDo) FirstOrInit() (*models.FileVersion, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.FileVersion), nil
	}
}

func (f fileVersionDo) FirstOrCreate() (*models.FileVersion, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.FileVersion), nil
	}
}

func (f fileVersionDo) FindByPage(offset int, limit int) (result []*models.FileVersion, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fileVersionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fileVersionDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fileVersionDo) Delete(models ...*models.FileVersion) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fileVersionDo) withDO(do gen.Dao) *fileVersionDo {
	f.DO = *do.(*gen.DO)
	return f
}
