// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gosync/internal/models"
)

func newFile(db *gorm.DB, opts ...gen.DOOption) file {
	_file := file{}

	_file.fileDo.UseDB(db, opts...)
	_file.fileDo.UseModel(&models.File{})

	tableName := _file.fileDo.TableName()
	_file.ALL = field.NewAsterisk(tableName)
	_file.ID = field.NewField(tableName, "id")
	_file.UserID = field.NewField(tableName, "user_id")
	_file.DirectoryID = field.NewField(tableName, "directory_id")
	_file.Name = field.NewString(tableName, "name")
	_file.CurrentVersionID = field.NewField(tableName, "current_version_id")
	_file.ContentHash = field.NewString(tableName, "content_hash")
	_file.CreatedAt = field.NewTime(tableName, "created_at")
	_file.UpdatedAt = field.NewTime(tableName, "updated_at")
	_file.DeletedAt = field.NewTime(tableName, "deleted_at")
	_file.Versions = fileHasManyVersions{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Versions", "models.FileVersion"),
		File: struct {
			field.RelationField
			User struct {
				field.RelationField
				RootDirectory struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					Parent struct {
						field.RelationField
					}
					Children struct {
						field.RelationField
					}
					Files struct {
						field.RelationField
					}
				}
				Devices struct {
					field.RelationField
					User struct {
						field.RelationField
					}
				}
				Directories struct {
					field.RelationField
				}
				Files struct {
					field.RelationField
				}
				Events struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					File struct {
						field.RelationField
					}
					Directory struct {
						field.RelationField
					}
				}
			}
			Directory struct {
				field.RelationField
			}
			CurrentVersion struct {
				field.RelationField
			}
			Versions struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Versions.File", "models.File"),
			User: struct {
				field.RelationField
				RootDirectory struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					Parent struct {
						field.RelationField
					}
					Children struct {
						field.RelationField
					}
					Files struct {
						field.RelationField
					}
				}
				Devices struct {
					field.RelationField
					User struct {
						field.RelationField
					}
				}
				Directories struct {
					field.RelationField
				}
				Files struct {
					field.RelationField
				}
				Events struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					File struct {
						field.RelationField
					}
					Directory struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Versions.File.User", "models.User"),
				RootDirectory: struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					Parent struct {
						field.RelationField
					}
					Children struct {
						field.RelationField
					}
					Files struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Versions.File.User.RootDirectory", "models.Directory"),
					User: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Versions.File.User.RootDirectory.User", "models.User"),
					},
					Parent: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Versions.File.User.RootDirectory.Parent", "models.Directory"),
					},
					Children: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Versions.File.User.RootDirectory.Children", "models.Directory"),
					},
					Files: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Versions.File.User.RootDirectory.Files", "models.File"),
					},
				},
				Devices: struct {
					field.RelationField
					User struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Versions.File.User.Devices", "models.Device"),
					User: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Versions.File.User.Devices.User", "models.User"),
					},
				},
				Directories: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Versions.File.User.Directories", "models.Directory"),
				},
				Files: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Versions.File.User.Files", "models.File"),
				},
				Events: struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					File struct {
						field.RelationField
					}
					Directory struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Versions.File.User.Events", "models.Event"),
					User: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Versions.File.User.Events.User", "models.User"),
					},
					File: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Versions.File.User.Events.File", "models.File"),
					},
					Directory: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Versions.File.User.Events.Directory", "models.Directory"),
					},
				},
			},
			Directory: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Versions.File.Directory", "models.Directory"),
			},
			CurrentVersion: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Versions.File.CurrentVersion", "models.FileVersion"),
			},
			Versions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Versions.File.Versions", "models.FileVersion"),
			},
		},
	}

	_file.User = fileBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "models.User"),
	}

	_file.Directory = fileBelongsToDirectory{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Directory", "models.Directory"),
	}

	_file.CurrentVersion = fileBelongsToCurrentVersion{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("CurrentVersion", "models.FileVersion"),
	}

	_file.fillFieldMap()

	return _file
}

type file struct {
	fileDo fileDo

	ALL              field.Asterisk
	ID               field.Field
	UserID           field.Field
	DirectoryID      field.Field
	Name             field.String
	CurrentVersionID field.Field
	ContentHash      field.String
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Time
	Versions         fileHasManyVersions

	User fileBelongsToUser

	Directory fileBelongsToDirectory

	CurrentVersion fileBelongsToCurrentVersion

	fieldMap map[string]field.Expr
}

func (f file) Table(newTableName string) *file {
	f.fileDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f file) As(alias string) *file {
	f.fileDo.DO = *(f.fileDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *file) updateTableName(table string) *file {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewField(table, "id")
	f.UserID = field.NewField(table, "user_id")
	f.DirectoryID = field.NewField(table, "directory_id")
	f.Name = field.NewString(table, "name")
	f.CurrentVersionID = field.NewField(table, "current_version_id")
	f.ContentHash = field.NewString(table, "content_hash")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")
	f.DeletedAt = field.NewTime(table, "deleted_at")

	f.fillFieldMap()

	return f
}

func (f *file) WithContext(ctx context.Context) IFileDo { return f.fileDo.WithContext(ctx) }

func (f file) TableName() string { return f.fileDo.TableName() }

func (f file) Alias() string { return f.fileDo.Alias() }

func (f file) Columns(cols ...field.Expr) gen.Columns { return f.fileDo.Columns(cols...) }

func (f *file) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *file) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 13)
	f.fieldMap["id"] = f.ID
	f.fieldMap["user_id"] = f.UserID
	f.fieldMap["directory_id"] = f.DirectoryID
	f.fieldMap["name"] = f.Name
	f.fieldMap["current_version_id"] = f.CurrentVersionID
	f.fieldMap["content_hash"] = f.ContentHash
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
	f.fieldMap["deleted_at"] = f.DeletedAt

}

func (f file) clone(db *gorm.DB) file {
	f.fileDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f file) replaceDB(db *gorm.DB) file {
	f.fileDo.ReplaceDB(db)
	return f
}

type fileHasManyVersions struct {
	db *gorm.DB

	field.RelationField

	File struct {
		field.RelationField
		User struct {
			field.RelationField
			RootDirectory struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Parent struct {
					field.RelationField
				}
				Children struct {
					field.RelationField
				}
				Files struct {
					field.RelationField
				}
			}
			Devices struct {
				field.RelationField
				User struct {
					field.RelationField
				}
			}
			Directories struct {
				field.RelationField
			}
			Files struct {
				field.RelationField
			}
			Events struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				File struct {
					field.RelationField
				}
				Directory struct {
					field.RelationField
				}
			}
		}
		Directory struct {
			field.RelationField
		}
		CurrentVersion struct {
			field.RelationField
		}
		Versions struct {
			field.RelationField
		}
	}
}

func (a fileHasManyVersions) Where(conds ...field.Expr) *fileHasManyVersions {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a fileHasManyVersions) WithContext(ctx context.Context) *fileHasManyVersions {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a fileHasManyVersions) Session(session *gorm.Session) *fileHasManyVersions {
	a.db = a.db.Session(session)
	return &a
}

func (a fileHasManyVersions) Model(m *models.File) *fileHasManyVersionsTx {
	return &fileHasManyVersionsTx{a.db.Model(m).Association(a.Name())}
}

type fileHasManyVersionsTx struct{ tx *gorm.Association }

func (a fileHasManyVersionsTx) Find() (result []*models.FileVersion, err error) {
	return result, a.tx.Find(&result)
}

func (a fileHasManyVersionsTx) Append(values ...*models.FileVersion) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a fileHasManyVersionsTx) Replace(values ...*models.FileVersion) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a fileHasManyVersionsTx) Delete(values ...*models.FileVersion) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a fileHasManyVersionsTx) Clear() error {
	return a.tx.Clear()
}

func (a fileHasManyVersionsTx) Count() int64 {
	return a.tx.Count()
}

type fileBelongsToUser struct {
	db *gorm.DB

	field.RelationField
}

func (a fileBelongsToUser) Where(conds ...field.Expr) *fileBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a fileBelongsToUser) WithContext(ctx context.Context) *fileBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a fileBelongsToUser) Session(session *gorm.Session) *fileBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a fileBelongsToUser) Model(m *models.File) *fileBelongsToUserTx {
	return &fileBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

type fileBelongsToUserTx struct{ tx *gorm.Association }

func (a fileBelongsToUserTx) Find() (result *models.User, err error) {
	return result, a.tx.Find(&result)
}

func (a fileBelongsToUserTx) Append(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a fileBelongsToUserTx) Replace(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a fileBelongsToUserTx) Delete(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a fileBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a fileBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

type fileBelongsToDirectory struct {
	db *gorm.DB

	field.RelationField
}

func (a fileBelongsToDirectory) Where(conds ...field.Expr) *fileBelongsToDirectory {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a fileBelongsToDirectory) WithContext(ctx context.Context) *fileBelongsToDirectory {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a fileBelongsToDirectory) Session(session *gorm.Session) *fileBelongsToDirectory {
	a.db = a.db.Session(session)
	return &a
}

func (a fileBelongsToDirectory) Model(m *models.File) *fileBelongsToDirectoryTx {
	return &fileBelongsToDirectoryTx{a.db.Model(m).Association(a.Name())}
}

type fileBelongsToDirectoryTx struct{ tx *gorm.Association }

func (a fileBelongsToDirectoryTx) Find() (result *models.Directory, err error) {
	return result, a.tx.Find(&result)
}

func (a fileBelongsToDirectoryTx) Append(values ...*models.Directory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a fileBelongsToDirectoryTx) Replace(values ...*models.Directory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a fileBelongsToDirectoryTx) Delete(values ...*models.Directory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a fileBelongsToDirectoryTx) Clear() error {
	return a.tx.Clear()
}

func (a fileBelongsToDirectoryTx) Count() int64 {
	return a.tx.Count()
}

type fileBelongsToCurrentVersion struct {
	db *gorm.DB

	field.RelationField
}

func (a fileBelongsToCurrentVersion) Where(conds ...field.Expr) *fileBelongsToCurrentVersion {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a fileBelongsToCurrentVersion) WithContext(ctx context.Context) *fileBelongsToCurrentVersion {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a fileBelongsToCurrentVersion) Session(session *gorm.Session) *fileBelongsToCurrentVersion {
	a.db = a.db.Session(session)
	return &a
}

func (a fileBelongsToCurrentVersion) Model(m *models.File) *fileBelongsToCurrentVersionTx {
	return &fileBelongsToCurrentVersionTx{a.db.Model(m).Association(a.Name())}
}

type fileBelongsToCurrentVersionTx struct{ tx *gorm.Association }

func (a fileBelongsToCurrentVersionTx) Find() (result *models.FileVersion, err error) {
	return result, a.tx.Find(&result)
}

func (a fileBelongsToCurrentVersionTx) Append(values ...*models.FileVersion) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a fileBelongsToCurrentVersionTx) Replace(values ...*models.FileVersion) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a fileBelongsToCurrentVersionTx) Delete(values ...*models.FileVersion) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a fileBelongsToCurrentVersionTx) Clear() error {
	return a.tx.Clear()
}

func (a fileBelongsToCurrentVersionTx) Count() int64 {
	return a.tx.Count()
}

type fileDo struct{ gen.DO }

type IFileDo interface {
	gen.SubQuery
	Debug() IFileDo
	WithContext(ctx context.Context) IFileDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFileDo
	WriteDB() IFileDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFileDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFileDo
	Not(conds ...gen.Condition) IFileDo
	Or(conds ...gen.Condition) IFileDo
	Select(conds ...field.Expr) IFileDo
	Where(conds ...gen.Condition) IFileDo
	Order(conds ...field.Expr) IFileDo
	Distinct(cols ...field.Expr) IFileDo
	Omit(cols ...field.Expr) IFileDo
	Join(table schema.Tabler, on ...field.Expr) IFileDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFileDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFileDo
	Group(cols ...field.Expr) IFileDo
	Having(conds ...gen.Condition) IFileDo
	Limit(limit int) IFileDo
	Offset(offset int) IFileDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFileDo
	Unscoped() IFileDo
	Create(values ...*models.File) error
	CreateInBatches(values []*models.File, batchSize int) error
	Save(values ...*models.File) error
	First() (*models.File, error)
	Take() (*models.File, error)
	Last() (*models.File, error)
	Find() ([]*models.File, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.File, err error)
	FindInBatches(result *[]*models.File, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.File) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFileDo
	Assign(attrs ...field.AssignExpr) IFileDo
	Joins(fields ...field.RelationField) IFileDo
	Preload(fields ...field.RelationField) IFileDo
	FirstOrInit() (*models.File, error)
	FirstOrCreate() (*models.File, error)
	FindByPage(offset int, limit int) (result []*models.File, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFileDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f fileDo) Debug() IFileDo {
	return f.withDO(f.DO.Debug())
}

func (f fileDo) WithContext(ctx context.Context) IFileDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fileDo) ReadDB() IFileDo {
	return f.Clauses(dbresolver.Read)
}

func (f fileDo) WriteDB() IFileDo {
	return f.Clauses(dbresolver.Write)
}

func (f fileDo) Session(config *gorm.Session) IFileDo {
	return f.withDO(f.DO.Session(config))
}

func (f fileDo) Clauses(conds ...clause.Expression) IFileDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fileDo) Returning(value interface{}, columns ...string) IFileDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fileDo) Not(conds ...gen.Condition) IFileDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fileDo) Or(conds ...gen.Condition) IFileDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fileDo) Select(conds ...field.Expr) IFileDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fileDo) Where(conds ...gen.Condition) IFileDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fileDo) Order(conds ...field.Expr) IFileDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fileDo) Distinct(cols ...field.Expr) IFileDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fileDo) Omit(cols ...field.Expr) IFileDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fileDo) Join(table schema.Tabler, on ...field.Expr) IFileDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fileDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFileDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fileDo) RightJoin(table schema.Tabler, on ...field.Expr) IFileDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fileDo) Group(cols ...field.Expr) IFileDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fileDo) Having(conds ...gen.Condition) IFileDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fileDo) Limit(limit int) IFileDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fileDo) Offset(offset int) IFileDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFileDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fileDo) Unscoped() IFileDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fileDo) Create(values ...*models.File) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fileDo) CreateInBatches(values []*models.File, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fileDo) Save(values ...*models.File) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fileDo) First() (*models.File, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.File), nil
	}
}

func (f fileDo) Take() (*models.File, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.File), nil
	}
}

func (f fileDo) Last() (*models.File, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.File), nil
	}
}

func (f fileDo) Find() ([]*models.File, error) {
	result, err := f.DO.Find()
	return result.([]*models.File), err
}

func (f fileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.File, err error) {
	buf := make([]*models.File, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fileDo) FindInBatches(result *[]*models.File, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fileDo) Attrs(attrs ...field.AssignExpr) IFileDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fileDo) Assign(attrs ...field.AssignExpr) IFileDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fileDo) Joins(fields ...field.RelationField) IFileDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fileDo) Preload(fields ...field.RelationField) IFileDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fileDo) FirstOrInit() (*models.File, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.File), nil
	}
}

func (f fileDo) FirstOrCreate() (*models.File, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.File), nil
	}
}

func (f fileDo) FindByPage(offset int, limit int) (result []*models.File, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fileDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fileDo) Delete(models ...*models.File) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fileDo) withDO(do gen.Dao) *fileDo {
	f.DO = *do.(*gen.DO)
	return f
}
