// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q            = new(Query)
	Device       *device
	Directory    *directory
	Event        *event
	File         *file
	FileVersion  *fileVersion
	RefreshToken *refreshToken
	User         *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Device = &Q.Device
	Directory = &Q.Directory
	Event = &Q.Event
	File = &Q.File
	FileVersion = &Q.FileVersion
	RefreshToken = &Q.RefreshToken
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		Device:       newDevice(db, opts...),
		Directory:    newDirectory(db, opts...),
		Event:        newEvent(db, opts...),
		File:         newFile(db, opts...),
		FileVersion:  newFileVersion(db, opts...),
		RefreshToken: newRefreshToken(db, opts...),
		User:         newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Device       device
	Directory    directory
	Event        event
	File         file
	FileVersion  fileVersion
	RefreshToken refreshToken
	User         user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Device:       q.Device.clone(db),
		Directory:    q.Directory.clone(db),
		Event:        q.Event.clone(db),
		File:         q.File.clone(db),
		FileVersion:  q.FileVersion.clone(db),
		RefreshToken: q.RefreshToken.clone(db),
		User:         q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Device:       q.Device.replaceDB(db),
		Directory:    q.Directory.replaceDB(db),
		Event:        q.Event.replaceDB(db),
		File:         q.File.replaceDB(db),
		FileVersion:  q.FileVersion.replaceDB(db),
		RefreshToken: q.RefreshToken.replaceDB(db),
		User:         q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Device       IDeviceDo
	Directory    IDirectoryDo
	Event        IEventDo
	File         IFileDo
	FileVersion  IFileVersionDo
	RefreshToken IRefreshTokenDo
	User         IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Device:       q.Device.WithContext(ctx),
		Directory:    q.Directory.WithContext(ctx),
		Event:        q.Event.WithContext(ctx),
		File:         q.File.WithContext(ctx),
		FileVersion:  q.FileVersion.WithContext(ctx),
		RefreshToken: q.RefreshToken.WithContext(ctx),
		User:         q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
