// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gosync/internal/models"
)

func newRefreshToken(db *gorm.DB, opts ...gen.DOOption) refreshToken {
	_refreshToken := refreshToken{}

	_refreshToken.refreshTokenDo.UseDB(db, opts...)
	_refreshToken.refreshTokenDo.UseModel(&models.RefreshToken{})

	tableName := _refreshToken.refreshTokenDo.TableName()
	_refreshToken.ALL = field.NewAsterisk(tableName)
	_refreshToken.ID = field.NewField(tableName, "id")
	_refreshToken.UserID = field.NewField(tableName, "user_id")
	_refreshToken.TokenHash = field.NewString(tableName, "token_hash")
	_refreshToken.ExpiresAt = field.NewTime(tableName, "expires_at")
	_refreshToken.RevokedAt = field.NewTime(tableName, "revoked_at")
	_refreshToken.CreatedAt = field.NewTime(tableName, "created_at")
	_refreshToken.User = refreshTokenBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "models.User"),
		Devices: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.Devices", "models.Device"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Devices.User", "models.User"),
			},
		},
		Directories: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Parent struct {
				field.RelationField
			}
			Children struct {
				field.RelationField
			}
			Files struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Directory struct {
					field.RelationField
				}
				CurrentVersion struct {
					field.RelationField
					File struct {
						field.RelationField
					}
				}
				Versions struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("User.Directories", "models.Directory"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Directories.User", "models.User"),
			},
			Parent: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Directories.Parent", "models.Directory"),
			},
			Children: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Directories.Children", "models.Directory"),
			},
			Files: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Directory struct {
					field.RelationField
				}
				CurrentVersion struct {
					field.RelationField
					File struct {
						field.RelationField
					}
				}
				Versions struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("User.Directories.Files", "models.File"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.Directories.Files.User", "models.User"),
				},
				Directory: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.Directories.Files.Directory", "models.Directory"),
				},
				CurrentVersion: struct {
					field.RelationField
					File struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("User.Directories.Files.CurrentVersion", "models.FileVersion"),
					File: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("User.Directories.Files.CurrentVersion.File", "models.File"),
					},
				},
				Versions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.Directories.Files.Versions", "models.FileVersion"),
				},
			},
		},
		Files: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.Files", "models.File"),
		},
		Events: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Device struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.Events", "models.SyncEvent"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Events.User", "models.User"),
			},
			Device: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Events.Device", "models.Device"),
			},
		},
	}

	_refreshToken.fillFieldMap()

	return _refreshToken
}

type refreshToken struct {
	refreshTokenDo refreshTokenDo

	ALL       field.Asterisk
	ID        field.Field
	UserID    field.Field
	TokenHash field.String
	ExpiresAt field.Time
	RevokedAt field.Time
	CreatedAt field.Time
	User      refreshTokenBelongsToUser

	fieldMap map[string]field.Expr
}

func (r refreshToken) Table(newTableName string) *refreshToken {
	r.refreshTokenDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r refreshToken) As(alias string) *refreshToken {
	r.refreshTokenDo.DO = *(r.refreshTokenDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *refreshToken) updateTableName(table string) *refreshToken {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewField(table, "id")
	r.UserID = field.NewField(table, "user_id")
	r.TokenHash = field.NewString(table, "token_hash")
	r.ExpiresAt = field.NewTime(table, "expires_at")
	r.RevokedAt = field.NewTime(table, "revoked_at")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *refreshToken) WithContext(ctx context.Context) IRefreshTokenDo {
	return r.refreshTokenDo.WithContext(ctx)
}

func (r refreshToken) TableName() string { return r.refreshTokenDo.TableName() }

func (r refreshToken) Alias() string { return r.refreshTokenDo.Alias() }

func (r refreshToken) Columns(cols ...field.Expr) gen.Columns {
	return r.refreshTokenDo.Columns(cols...)
}

func (r *refreshToken) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *refreshToken) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 7)
	r.fieldMap["id"] = r.ID
	r.fieldMap["user_id"] = r.UserID
	r.fieldMap["token_hash"] = r.TokenHash
	r.fieldMap["expires_at"] = r.ExpiresAt
	r.fieldMap["revoked_at"] = r.RevokedAt
	r.fieldMap["created_at"] = r.CreatedAt

}

func (r refreshToken) clone(db *gorm.DB) refreshToken {
	r.refreshTokenDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r refreshToken) replaceDB(db *gorm.DB) refreshToken {
	r.refreshTokenDo.ReplaceDB(db)
	return r
}

type refreshTokenBelongsToUser struct {
	db *gorm.DB

	field.RelationField

	Devices struct {
		field.RelationField
		User struct {
			field.RelationField
		}
	}
	Directories struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		Parent struct {
			field.RelationField
		}
		Children struct {
			field.RelationField
		}
		Files struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Directory struct {
				field.RelationField
			}
			CurrentVersion struct {
				field.RelationField
				File struct {
					field.RelationField
				}
			}
			Versions struct {
				field.RelationField
			}
		}
	}
	Files struct {
		field.RelationField
	}
	Events struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		Device struct {
			field.RelationField
		}
	}
}

func (a refreshTokenBelongsToUser) Where(conds ...field.Expr) *refreshTokenBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a refreshTokenBelongsToUser) WithContext(ctx context.Context) *refreshTokenBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a refreshTokenBelongsToUser) Session(session *gorm.Session) *refreshTokenBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a refreshTokenBelongsToUser) Model(m *models.RefreshToken) *refreshTokenBelongsToUserTx {
	return &refreshTokenBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

type refreshTokenBelongsToUserTx struct{ tx *gorm.Association }

func (a refreshTokenBelongsToUserTx) Find() (result *models.User, err error) {
	return result, a.tx.Find(&result)
}

func (a refreshTokenBelongsToUserTx) Append(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a refreshTokenBelongsToUserTx) Replace(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a refreshTokenBelongsToUserTx) Delete(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a refreshTokenBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a refreshTokenBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

type refreshTokenDo struct{ gen.DO }

type IRefreshTokenDo interface {
	gen.SubQuery
	Debug() IRefreshTokenDo
	WithContext(ctx context.Context) IRefreshTokenDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRefreshTokenDo
	WriteDB() IRefreshTokenDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRefreshTokenDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRefreshTokenDo
	Not(conds ...gen.Condition) IRefreshTokenDo
	Or(conds ...gen.Condition) IRefreshTokenDo
	Select(conds ...field.Expr) IRefreshTokenDo
	Where(conds ...gen.Condition) IRefreshTokenDo
	Order(conds ...field.Expr) IRefreshTokenDo
	Distinct(cols ...field.Expr) IRefreshTokenDo
	Omit(cols ...field.Expr) IRefreshTokenDo
	Join(table schema.Tabler, on ...field.Expr) IRefreshTokenDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRefreshTokenDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRefreshTokenDo
	Group(cols ...field.Expr) IRefreshTokenDo
	Having(conds ...gen.Condition) IRefreshTokenDo
	Limit(limit int) IRefreshTokenDo
	Offset(offset int) IRefreshTokenDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRefreshTokenDo
	Unscoped() IRefreshTokenDo
	Create(values ...*models.RefreshToken) error
	CreateInBatches(values []*models.RefreshToken, batchSize int) error
	Save(values ...*models.RefreshToken) error
	First() (*models.RefreshToken, error)
	Take() (*models.RefreshToken, error)
	Last() (*models.RefreshToken, error)
	Find() ([]*models.RefreshToken, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.RefreshToken, err error)
	FindInBatches(result *[]*models.RefreshToken, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.RefreshToken) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRefreshTokenDo
	Assign(attrs ...field.AssignExpr) IRefreshTokenDo
	Joins(fields ...field.RelationField) IRefreshTokenDo
	Preload(fields ...field.RelationField) IRefreshTokenDo
	FirstOrInit() (*models.RefreshToken, error)
	FirstOrCreate() (*models.RefreshToken, error)
	FindByPage(offset int, limit int) (result []*models.RefreshToken, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRefreshTokenDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r refreshTokenDo) Debug() IRefreshTokenDo {
	return r.withDO(r.DO.Debug())
}

func (r refreshTokenDo) WithContext(ctx context.Context) IRefreshTokenDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r refreshTokenDo) ReadDB() IRefreshTokenDo {
	return r.Clauses(dbresolver.Read)
}

func (r refreshTokenDo) WriteDB() IRefreshTokenDo {
	return r.Clauses(dbresolver.Write)
}

func (r refreshTokenDo) Session(config *gorm.Session) IRefreshTokenDo {
	return r.withDO(r.DO.Session(config))
}

func (r refreshTokenDo) Clauses(conds ...clause.Expression) IRefreshTokenDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r refreshTokenDo) Returning(value interface{}, columns ...string) IRefreshTokenDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r refreshTokenDo) Not(conds ...gen.Condition) IRefreshTokenDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r refreshTokenDo) Or(conds ...gen.Condition) IRefreshTokenDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r refreshTokenDo) Select(conds ...field.Expr) IRefreshTokenDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r refreshTokenDo) Where(conds ...gen.Condition) IRefreshTokenDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r refreshTokenDo) Order(conds ...field.Expr) IRefreshTokenDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r refreshTokenDo) Distinct(cols ...field.Expr) IRefreshTokenDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r refreshTokenDo) Omit(cols ...field.Expr) IRefreshTokenDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r refreshTokenDo) Join(table schema.Tabler, on ...field.Expr) IRefreshTokenDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r refreshTokenDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRefreshTokenDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r refreshTokenDo) RightJoin(table schema.Tabler, on ...field.Expr) IRefreshTokenDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r refreshTokenDo) Group(cols ...field.Expr) IRefreshTokenDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r refreshTokenDo) Having(conds ...gen.Condition) IRefreshTokenDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r refreshTokenDo) Limit(limit int) IRefreshTokenDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r refreshTokenDo) Offset(offset int) IRefreshTokenDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r refreshTokenDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRefreshTokenDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r refreshTokenDo) Unscoped() IRefreshTokenDo {
	return r.withDO(r.DO.Unscoped())
}

func (r refreshTokenDo) Create(values ...*models.RefreshToken) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r refreshTokenDo) CreateInBatches(values []*models.RefreshToken, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r refreshTokenDo) Save(values ...*models.RefreshToken) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r refreshTokenDo) First() (*models.RefreshToken, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.RefreshToken), nil
	}
}

func (r refreshTokenDo) Take() (*models.RefreshToken, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.RefreshToken), nil
	}
}

func (r refreshTokenDo) Last() (*models.RefreshToken, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.RefreshToken), nil
	}
}

func (r refreshTokenDo) Find() ([]*models.RefreshToken, error) {
	result, err := r.DO.Find()
	return result.([]*models.RefreshToken), err
}

func (r refreshTokenDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.RefreshToken, err error) {
	buf := make([]*models.RefreshToken, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r refreshTokenDo) FindInBatches(result *[]*models.RefreshToken, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r refreshTokenDo) Attrs(attrs ...field.AssignExpr) IRefreshTokenDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r refreshTokenDo) Assign(attrs ...field.AssignExpr) IRefreshTokenDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r refreshTokenDo) Joins(fields ...field.RelationField) IRefreshTokenDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r refreshTokenDo) Preload(fields ...field.RelationField) IRefreshTokenDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r refreshTokenDo) FirstOrInit() (*models.RefreshToken, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.RefreshToken), nil
	}
}

func (r refreshTokenDo) FirstOrCreate() (*models.RefreshToken, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.RefreshToken), nil
	}
}

func (r refreshTokenDo) FindByPage(offset int, limit int) (result []*models.RefreshToken, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r refreshTokenDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r refreshTokenDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r refreshTokenDo) Delete(models ...*models.RefreshToken) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *refreshTokenDo) withDO(do gen.Dao) *refreshTokenDo {
	r.DO = *do.(*gen.DO)
	return r
}
