// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gosync/internal/models"
)

func newSyncEvent(db *gorm.DB, opts ...gen.DOOption) syncEvent {
	_syncEvent := syncEvent{}

	_syncEvent.syncEventDo.UseDB(db, opts...)
	_syncEvent.syncEventDo.UseModel(&models.SyncEvent{})

	tableName := _syncEvent.syncEventDo.TableName()
	_syncEvent.ALL = field.NewAsterisk(tableName)
	_syncEvent.ID = field.NewUint64(tableName, "id")
	_syncEvent.UserID = field.NewField(tableName, "user_id")
	_syncEvent.DeviceID = field.NewField(tableName, "device_id")
	_syncEvent.Operation = field.NewString(tableName, "operation")
	_syncEvent.ResourceType = field.NewString(tableName, "resource_type")
	_syncEvent.ResourceID = field.NewField(tableName, "resource_id")
	_syncEvent.CreatedAt = field.NewTime(tableName, "created_at")
	_syncEvent.User = syncEventBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "models.User"),
		Devices: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.Devices", "models.Device"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Devices.User", "models.User"),
			},
		},
		Directories: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Parent struct {
				field.RelationField
			}
			Children struct {
				field.RelationField
			}
			Files struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Directory struct {
					field.RelationField
				}
				CurrentVersion struct {
					field.RelationField
					File struct {
						field.RelationField
					}
				}
				Versions struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("User.Directories", "models.Directory"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Directories.User", "models.User"),
			},
			Parent: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Directories.Parent", "models.Directory"),
			},
			Children: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Directories.Children", "models.Directory"),
			},
			Files: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Directory struct {
					field.RelationField
				}
				CurrentVersion struct {
					field.RelationField
					File struct {
						field.RelationField
					}
				}
				Versions struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("User.Directories.Files", "models.File"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.Directories.Files.User", "models.User"),
				},
				Directory: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.Directories.Files.Directory", "models.Directory"),
				},
				CurrentVersion: struct {
					field.RelationField
					File struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("User.Directories.Files.CurrentVersion", "models.FileVersion"),
					File: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("User.Directories.Files.CurrentVersion.File", "models.File"),
					},
				},
				Versions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.Directories.Files.Versions", "models.FileVersion"),
				},
			},
		},
		Files: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.Files", "models.File"),
		},
		Events: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Device struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.Events", "models.SyncEvent"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Events.User", "models.User"),
			},
			Device: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Events.Device", "models.Device"),
			},
		},
	}

	_syncEvent.Device = syncEventBelongsToDevice{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Device", "models.Device"),
	}

	_syncEvent.fillFieldMap()

	return _syncEvent
}

type syncEvent struct {
	syncEventDo syncEventDo

	ALL          field.Asterisk
	ID           field.Uint64
	UserID       field.Field
	DeviceID     field.Field
	Operation    field.String
	ResourceType field.String
	ResourceID   field.Field
	CreatedAt    field.Time
	User         syncEventBelongsToUser

	Device syncEventBelongsToDevice

	fieldMap map[string]field.Expr
}

func (s syncEvent) Table(newTableName string) *syncEvent {
	s.syncEventDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s syncEvent) As(alias string) *syncEvent {
	s.syncEventDo.DO = *(s.syncEventDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *syncEvent) updateTableName(table string) *syncEvent {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.UserID = field.NewField(table, "user_id")
	s.DeviceID = field.NewField(table, "device_id")
	s.Operation = field.NewString(table, "operation")
	s.ResourceType = field.NewString(table, "resource_type")
	s.ResourceID = field.NewField(table, "resource_id")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *syncEvent) WithContext(ctx context.Context) ISyncEventDo {
	return s.syncEventDo.WithContext(ctx)
}

func (s syncEvent) TableName() string { return s.syncEventDo.TableName() }

func (s syncEvent) Alias() string { return s.syncEventDo.Alias() }

func (s syncEvent) Columns(cols ...field.Expr) gen.Columns { return s.syncEventDo.Columns(cols...) }

func (s *syncEvent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *syncEvent) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 9)
	s.fieldMap["id"] = s.ID
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["device_id"] = s.DeviceID
	s.fieldMap["operation"] = s.Operation
	s.fieldMap["resource_type"] = s.ResourceType
	s.fieldMap["resource_id"] = s.ResourceID
	s.fieldMap["created_at"] = s.CreatedAt

}

func (s syncEvent) clone(db *gorm.DB) syncEvent {
	s.syncEventDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s syncEvent) replaceDB(db *gorm.DB) syncEvent {
	s.syncEventDo.ReplaceDB(db)
	return s
}

type syncEventBelongsToUser struct {
	db *gorm.DB

	field.RelationField

	Devices struct {
		field.RelationField
		User struct {
			field.RelationField
		}
	}
	Directories struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		Parent struct {
			field.RelationField
		}
		Children struct {
			field.RelationField
		}
		Files struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Directory struct {
				field.RelationField
			}
			CurrentVersion struct {
				field.RelationField
				File struct {
					field.RelationField
				}
			}
			Versions struct {
				field.RelationField
			}
		}
	}
	Files struct {
		field.RelationField
	}
	Events struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		Device struct {
			field.RelationField
		}
	}
}

func (a syncEventBelongsToUser) Where(conds ...field.Expr) *syncEventBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a syncEventBelongsToUser) WithContext(ctx context.Context) *syncEventBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a syncEventBelongsToUser) Session(session *gorm.Session) *syncEventBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a syncEventBelongsToUser) Model(m *models.SyncEvent) *syncEventBelongsToUserTx {
	return &syncEventBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

type syncEventBelongsToUserTx struct{ tx *gorm.Association }

func (a syncEventBelongsToUserTx) Find() (result *models.User, err error) {
	return result, a.tx.Find(&result)
}

func (a syncEventBelongsToUserTx) Append(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a syncEventBelongsToUserTx) Replace(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a syncEventBelongsToUserTx) Delete(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a syncEventBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a syncEventBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

type syncEventBelongsToDevice struct {
	db *gorm.DB

	field.RelationField
}

func (a syncEventBelongsToDevice) Where(conds ...field.Expr) *syncEventBelongsToDevice {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a syncEventBelongsToDevice) WithContext(ctx context.Context) *syncEventBelongsToDevice {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a syncEventBelongsToDevice) Session(session *gorm.Session) *syncEventBelongsToDevice {
	a.db = a.db.Session(session)
	return &a
}

func (a syncEventBelongsToDevice) Model(m *models.SyncEvent) *syncEventBelongsToDeviceTx {
	return &syncEventBelongsToDeviceTx{a.db.Model(m).Association(a.Name())}
}

type syncEventBelongsToDeviceTx struct{ tx *gorm.Association }

func (a syncEventBelongsToDeviceTx) Find() (result *models.Device, err error) {
	return result, a.tx.Find(&result)
}

func (a syncEventBelongsToDeviceTx) Append(values ...*models.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a syncEventBelongsToDeviceTx) Replace(values ...*models.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a syncEventBelongsToDeviceTx) Delete(values ...*models.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a syncEventBelongsToDeviceTx) Clear() error {
	return a.tx.Clear()
}

func (a syncEventBelongsToDeviceTx) Count() int64 {
	return a.tx.Count()
}

type syncEventDo struct{ gen.DO }

type ISyncEventDo interface {
	gen.SubQuery
	Debug() ISyncEventDo
	WithContext(ctx context.Context) ISyncEventDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISyncEventDo
	WriteDB() ISyncEventDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISyncEventDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISyncEventDo
	Not(conds ...gen.Condition) ISyncEventDo
	Or(conds ...gen.Condition) ISyncEventDo
	Select(conds ...field.Expr) ISyncEventDo
	Where(conds ...gen.Condition) ISyncEventDo
	Order(conds ...field.Expr) ISyncEventDo
	Distinct(cols ...field.Expr) ISyncEventDo
	Omit(cols ...field.Expr) ISyncEventDo
	Join(table schema.Tabler, on ...field.Expr) ISyncEventDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISyncEventDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISyncEventDo
	Group(cols ...field.Expr) ISyncEventDo
	Having(conds ...gen.Condition) ISyncEventDo
	Limit(limit int) ISyncEventDo
	Offset(offset int) ISyncEventDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISyncEventDo
	Unscoped() ISyncEventDo
	Create(values ...*models.SyncEvent) error
	CreateInBatches(values []*models.SyncEvent, batchSize int) error
	Save(values ...*models.SyncEvent) error
	First() (*models.SyncEvent, error)
	Take() (*models.SyncEvent, error)
	Last() (*models.SyncEvent, error)
	Find() ([]*models.SyncEvent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SyncEvent, err error)
	FindInBatches(result *[]*models.SyncEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SyncEvent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISyncEventDo
	Assign(attrs ...field.AssignExpr) ISyncEventDo
	Joins(fields ...field.RelationField) ISyncEventDo
	Preload(fields ...field.RelationField) ISyncEventDo
	FirstOrInit() (*models.SyncEvent, error)
	FirstOrCreate() (*models.SyncEvent, error)
	FindByPage(offset int, limit int) (result []*models.SyncEvent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISyncEventDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s syncEventDo) Debug() ISyncEventDo {
	return s.withDO(s.DO.Debug())
}

func (s syncEventDo) WithContext(ctx context.Context) ISyncEventDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s syncEventDo) ReadDB() ISyncEventDo {
	return s.Clauses(dbresolver.Read)
}

func (s syncEventDo) WriteDB() ISyncEventDo {
	return s.Clauses(dbresolver.Write)
}

func (s syncEventDo) Session(config *gorm.Session) ISyncEventDo {
	return s.withDO(s.DO.Session(config))
}

func (s syncEventDo) Clauses(conds ...clause.Expression) ISyncEventDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s syncEventDo) Returning(value interface{}, columns ...string) ISyncEventDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s syncEventDo) Not(conds ...gen.Condition) ISyncEventDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s syncEventDo) Or(conds ...gen.Condition) ISyncEventDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s syncEventDo) Select(conds ...field.Expr) ISyncEventDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s syncEventDo) Where(conds ...gen.Condition) ISyncEventDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s syncEventDo) Order(conds ...field.Expr) ISyncEventDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s syncEventDo) Distinct(cols ...field.Expr) ISyncEventDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s syncEventDo) Omit(cols ...field.Expr) ISyncEventDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s syncEventDo) Join(table schema.Tabler, on ...field.Expr) ISyncEventDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s syncEventDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISyncEventDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s syncEventDo) RightJoin(table schema.Tabler, on ...field.Expr) ISyncEventDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s syncEventDo) Group(cols ...field.Expr) ISyncEventDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s syncEventDo) Having(conds ...gen.Condition) ISyncEventDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s syncEventDo) Limit(limit int) ISyncEventDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s syncEventDo) Offset(offset int) ISyncEventDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s syncEventDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISyncEventDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s syncEventDo) Unscoped() ISyncEventDo {
	return s.withDO(s.DO.Unscoped())
}

func (s syncEventDo) Create(values ...*models.SyncEvent) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s syncEventDo) CreateInBatches(values []*models.SyncEvent, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s syncEventDo) Save(values ...*models.SyncEvent) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s syncEventDo) First() (*models.SyncEvent, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SyncEvent), nil
	}
}

func (s syncEventDo) Take() (*models.SyncEvent, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SyncEvent), nil
	}
}

func (s syncEventDo) Last() (*models.SyncEvent, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SyncEvent), nil
	}
}

func (s syncEventDo) Find() ([]*models.SyncEvent, error) {
	result, err := s.DO.Find()
	return result.([]*models.SyncEvent), err
}

func (s syncEventDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SyncEvent, err error) {
	buf := make([]*models.SyncEvent, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s syncEventDo) FindInBatches(result *[]*models.SyncEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s syncEventDo) Attrs(attrs ...field.AssignExpr) ISyncEventDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s syncEventDo) Assign(attrs ...field.AssignExpr) ISyncEventDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s syncEventDo) Joins(fields ...field.RelationField) ISyncEventDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s syncEventDo) Preload(fields ...field.RelationField) ISyncEventDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s syncEventDo) FirstOrInit() (*models.SyncEvent, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SyncEvent), nil
	}
}

func (s syncEventDo) FirstOrCreate() (*models.SyncEvent, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SyncEvent), nil
	}
}

func (s syncEventDo) FindByPage(offset int, limit int) (result []*models.SyncEvent, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s syncEventDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s syncEventDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s syncEventDo) Delete(models ...*models.SyncEvent) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *syncEventDo) withDO(do gen.Dao) *syncEventDo {
	s.DO = *do.(*gen.DO)
	return s
}
