// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gosync/internal/models"
)

func newUser(db *gorm.DB, opts ...gen.DOOption) user {
	_user := user{}

	_user.userDo.UseDB(db, opts...)
	_user.userDo.UseModel(&models.User{})

	tableName := _user.userDo.TableName()
	_user.ALL = field.NewAsterisk(tableName)
	_user.ID = field.NewField(tableName, "id")
	_user.Name = field.NewString(tableName, "name")
	_user.Email = field.NewString(tableName, "email")
	_user.PasswordHash = field.NewString(tableName, "password_hash")
	_user.Role = field.NewString(tableName, "role")
	_user.RootDirectoryID = field.NewField(tableName, "root_directory_id")
	_user.CreatedAt = field.NewTime(tableName, "created_at")
	_user.UpdatedAt = field.NewTime(tableName, "updated_at")
	_user.Devices = userHasManyDevices{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Devices", "models.Device"),
		User: struct {
			field.RelationField
			RootDirectory struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Parent struct {
					field.RelationField
				}
				Children struct {
					field.RelationField
				}
				Files struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					Directory struct {
						field.RelationField
					}
					CurrentVersion struct {
						field.RelationField
						File struct {
							field.RelationField
						}
					}
					Versions struct {
						field.RelationField
					}
				}
			}
			Devices struct {
				field.RelationField
			}
			Directories struct {
				field.RelationField
			}
			Files struct {
				field.RelationField
			}
			Events struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				File struct {
					field.RelationField
				}
				Directory struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Devices.User", "models.User"),
			RootDirectory: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Parent struct {
					field.RelationField
				}
				Children struct {
					field.RelationField
				}
				Files struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					Directory struct {
						field.RelationField
					}
					CurrentVersion struct {
						field.RelationField
						File struct {
							field.RelationField
						}
					}
					Versions struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Devices.User.RootDirectory", "models.Directory"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Devices.User.RootDirectory.User", "models.User"),
				},
				Parent: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Devices.User.RootDirectory.Parent", "models.Directory"),
				},
				Children: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Devices.User.RootDirectory.Children", "models.Directory"),
				},
				Files: struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					Directory struct {
						field.RelationField
					}
					CurrentVersion struct {
						field.RelationField
						File struct {
							field.RelationField
						}
					}
					Versions struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Devices.User.RootDirectory.Files", "models.File"),
					User: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Devices.User.RootDirectory.Files.User", "models.User"),
					},
					Directory: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Devices.User.RootDirectory.Files.Directory", "models.Directory"),
					},
					CurrentVersion: struct {
						field.RelationField
						File struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Devices.User.RootDirectory.Files.CurrentVersion", "models.FileVersion"),
						File: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Devices.User.RootDirectory.Files.CurrentVersion.File", "models.File"),
						},
					},
					Versions: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Devices.User.RootDirectory.Files.Versions", "models.FileVersion"),
					},
				},
			},
			Devices: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Devices.User.Devices", "models.Device"),
			},
			Directories: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Devices.User.Directories", "models.Directory"),
			},
			Files: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Devices.User.Files", "models.File"),
			},
			Events: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				File struct {
					field.RelationField
				}
				Directory struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Devices.User.Events", "models.Event"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Devices.User.Events.User", "models.User"),
				},
				File: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Devices.User.Events.File", "models.File"),
				},
				Directory: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Devices.User.Events.Directory", "models.Directory"),
				},
			},
		},
	}

	_user.Directories = userHasManyDirectories{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Directories", "models.Directory"),
	}

	_user.Files = userHasManyFiles{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Files", "models.File"),
	}

	_user.Events = userHasManyEvents{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Events", "models.Event"),
	}

	_user.RootDirectory = userBelongsToRootDirectory{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("RootDirectory", "models.Directory"),
	}

	_user.fillFieldMap()

	return _user
}

type user struct {
	userDo userDo

	ALL             field.Asterisk
	ID              field.Field
	Name            field.String
	Email           field.String
	PasswordHash    field.String
	Role            field.String
	RootDirectoryID field.Field
	CreatedAt       field.Time
	UpdatedAt       field.Time
	Devices         userHasManyDevices

	Directories userHasManyDirectories

	Files userHasManyFiles

	Events userHasManyEvents

	RootDirectory userBelongsToRootDirectory

	fieldMap map[string]field.Expr
}

func (u user) Table(newTableName string) *user {
	u.userDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u user) As(alias string) *user {
	u.userDo.DO = *(u.userDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *user) updateTableName(table string) *user {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewField(table, "id")
	u.Name = field.NewString(table, "name")
	u.Email = field.NewString(table, "email")
	u.PasswordHash = field.NewString(table, "password_hash")
	u.Role = field.NewString(table, "role")
	u.RootDirectoryID = field.NewField(table, "root_directory_id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *user) WithContext(ctx context.Context) IUserDo { return u.userDo.WithContext(ctx) }

func (u user) TableName() string { return u.userDo.TableName() }

func (u user) Alias() string { return u.userDo.Alias() }

func (u user) Columns(cols ...field.Expr) gen.Columns { return u.userDo.Columns(cols...) }

func (u *user) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *user) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 13)
	u.fieldMap["id"] = u.ID
	u.fieldMap["name"] = u.Name
	u.fieldMap["email"] = u.Email
	u.fieldMap["password_hash"] = u.PasswordHash
	u.fieldMap["role"] = u.Role
	u.fieldMap["root_directory_id"] = u.RootDirectoryID
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt

}

func (u user) clone(db *gorm.DB) user {
	u.userDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u user) replaceDB(db *gorm.DB) user {
	u.userDo.ReplaceDB(db)
	return u
}

type userHasManyDevices struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
		RootDirectory struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Parent struct {
				field.RelationField
			}
			Children struct {
				field.RelationField
			}
			Files struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Directory struct {
					field.RelationField
				}
				CurrentVersion struct {
					field.RelationField
					File struct {
						field.RelationField
					}
				}
				Versions struct {
					field.RelationField
				}
			}
		}
		Devices struct {
			field.RelationField
		}
		Directories struct {
			field.RelationField
		}
		Files struct {
			field.RelationField
		}
		Events struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			File struct {
				field.RelationField
			}
			Directory struct {
				field.RelationField
			}
		}
	}
}

func (a userHasManyDevices) Where(conds ...field.Expr) *userHasManyDevices {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userHasManyDevices) WithContext(ctx context.Context) *userHasManyDevices {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userHasManyDevices) Session(session *gorm.Session) *userHasManyDevices {
	a.db = a.db.Session(session)
	return &a
}

func (a userHasManyDevices) Model(m *models.User) *userHasManyDevicesTx {
	return &userHasManyDevicesTx{a.db.Model(m).Association(a.Name())}
}

type userHasManyDevicesTx struct{ tx *gorm.Association }

func (a userHasManyDevicesTx) Find() (result []*models.Device, err error) {
	return result, a.tx.Find(&result)
}

func (a userHasManyDevicesTx) Append(values ...*models.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userHasManyDevicesTx) Replace(values ...*models.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userHasManyDevicesTx) Delete(values ...*models.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userHasManyDevicesTx) Clear() error {
	return a.tx.Clear()
}

func (a userHasManyDevicesTx) Count() int64 {
	return a.tx.Count()
}

type userHasManyDirectories struct {
	db *gorm.DB

	field.RelationField
}

func (a userHasManyDirectories) Where(conds ...field.Expr) *userHasManyDirectories {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userHasManyDirectories) WithContext(ctx context.Context) *userHasManyDirectories {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userHasManyDirectories) Session(session *gorm.Session) *userHasManyDirectories {
	a.db = a.db.Session(session)
	return &a
}

func (a userHasManyDirectories) Model(m *models.User) *userHasManyDirectoriesTx {
	return &userHasManyDirectoriesTx{a.db.Model(m).Association(a.Name())}
}

type userHasManyDirectoriesTx struct{ tx *gorm.Association }

func (a userHasManyDirectoriesTx) Find() (result []*models.Directory, err error) {
	return result, a.tx.Find(&result)
}

func (a userHasManyDirectoriesTx) Append(values ...*models.Directory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userHasManyDirectoriesTx) Replace(values ...*models.Directory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userHasManyDirectoriesTx) Delete(values ...*models.Directory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userHasManyDirectoriesTx) Clear() error {
	return a.tx.Clear()
}

func (a userHasManyDirectoriesTx) Count() int64 {
	return a.tx.Count()
}

type userHasManyFiles struct {
	db *gorm.DB

	field.RelationField
}

func (a userHasManyFiles) Where(conds ...field.Expr) *userHasManyFiles {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userHasManyFiles) WithContext(ctx context.Context) *userHasManyFiles {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userHasManyFiles) Session(session *gorm.Session) *userHasManyFiles {
	a.db = a.db.Session(session)
	return &a
}

func (a userHasManyFiles) Model(m *models.User) *userHasManyFilesTx {
	return &userHasManyFilesTx{a.db.Model(m).Association(a.Name())}
}

type userHasManyFilesTx struct{ tx *gorm.Association }

func (a userHasManyFilesTx) Find() (result []*models.File, err error) {
	return result, a.tx.Find(&result)
}

func (a userHasManyFilesTx) Append(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userHasManyFilesTx) Replace(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userHasManyFilesTx) Delete(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userHasManyFilesTx) Clear() error {
	return a.tx.Clear()
}

func (a userHasManyFilesTx) Count() int64 {
	return a.tx.Count()
}

type userHasManyEvents struct {
	db *gorm.DB

	field.RelationField
}

func (a userHasManyEvents) Where(conds ...field.Expr) *userHasManyEvents {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userHasManyEvents) WithContext(ctx context.Context) *userHasManyEvents {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userHasManyEvents) Session(session *gorm.Session) *userHasManyEvents {
	a.db = a.db.Session(session)
	return &a
}

func (a userHasManyEvents) Model(m *models.User) *userHasManyEventsTx {
	return &userHasManyEventsTx{a.db.Model(m).Association(a.Name())}
}

type userHasManyEventsTx struct{ tx *gorm.Association }

func (a userHasManyEventsTx) Find() (result []*models.Event, err error) {
	return result, a.tx.Find(&result)
}

func (a userHasManyEventsTx) Append(values ...*models.Event) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userHasManyEventsTx) Replace(values ...*models.Event) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userHasManyEventsTx) Delete(values ...*models.Event) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userHasManyEventsTx) Clear() error {
	return a.tx.Clear()
}

func (a userHasManyEventsTx) Count() int64 {
	return a.tx.Count()
}

type userBelongsToRootDirectory struct {
	db *gorm.DB

	field.RelationField
}

func (a userBelongsToRootDirectory) Where(conds ...field.Expr) *userBelongsToRootDirectory {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userBelongsToRootDirectory) WithContext(ctx context.Context) *userBelongsToRootDirectory {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userBelongsToRootDirectory) Session(session *gorm.Session) *userBelongsToRootDirectory {
	a.db = a.db.Session(session)
	return &a
}

func (a userBelongsToRootDirectory) Model(m *models.User) *userBelongsToRootDirectoryTx {
	return &userBelongsToRootDirectoryTx{a.db.Model(m).Association(a.Name())}
}

type userBelongsToRootDirectoryTx struct{ tx *gorm.Association }

func (a userBelongsToRootDirectoryTx) Find() (result *models.Directory, err error) {
	return result, a.tx.Find(&result)
}

func (a userBelongsToRootDirectoryTx) Append(values ...*models.Directory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userBelongsToRootDirectoryTx) Replace(values ...*models.Directory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userBelongsToRootDirectoryTx) Delete(values ...*models.Directory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userBelongsToRootDirectoryTx) Clear() error {
	return a.tx.Clear()
}

func (a userBelongsToRootDirectoryTx) Count() int64 {
	return a.tx.Count()
}

type userDo struct{ gen.DO }

type IUserDo interface {
	gen.SubQuery
	Debug() IUserDo
	WithContext(ctx context.Context) IUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserDo
	WriteDB() IUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserDo
	Not(conds ...gen.Condition) IUserDo
	Or(conds ...gen.Condition) IUserDo
	Select(conds ...field.Expr) IUserDo
	Where(conds ...gen.Condition) IUserDo
	Order(conds ...field.Expr) IUserDo
	Distinct(cols ...field.Expr) IUserDo
	Omit(cols ...field.Expr) IUserDo
	Join(table schema.Tabler, on ...field.Expr) IUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserDo
	Group(cols ...field.Expr) IUserDo
	Having(conds ...gen.Condition) IUserDo
	Limit(limit int) IUserDo
	Offset(offset int) IUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserDo
	Unscoped() IUserDo
	Create(values ...*models.User) error
	CreateInBatches(values []*models.User, batchSize int) error
	Save(values ...*models.User) error
	First() (*models.User, error)
	Take() (*models.User, error)
	Last() (*models.User, error)
	Find() ([]*models.User, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.User, err error)
	FindInBatches(result *[]*models.User, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.User) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserDo
	Assign(attrs ...field.AssignExpr) IUserDo
	Joins(fields ...field.RelationField) IUserDo
	Preload(fields ...field.RelationField) IUserDo
	FirstOrInit() (*models.User, error)
	FirstOrCreate() (*models.User, error)
	FindByPage(offset int, limit int) (result []*models.User, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userDo) Debug() IUserDo {
	return u.withDO(u.DO.Debug())
}

func (u userDo) WithContext(ctx context.Context) IUserDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userDo) ReadDB() IUserDo {
	return u.Clauses(dbresolver.Read)
}

func (u userDo) WriteDB() IUserDo {
	return u.Clauses(dbresolver.Write)
}

func (u userDo) Session(config *gorm.Session) IUserDo {
	return u.withDO(u.DO.Session(config))
}

func (u userDo) Clauses(conds ...clause.Expression) IUserDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userDo) Returning(value interface{}, columns ...string) IUserDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userDo) Not(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userDo) Or(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userDo) Select(conds ...field.Expr) IUserDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userDo) Where(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userDo) Order(conds ...field.Expr) IUserDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userDo) Distinct(cols ...field.Expr) IUserDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userDo) Omit(cols ...field.Expr) IUserDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userDo) Join(table schema.Tabler, on ...field.Expr) IUserDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userDo) Group(cols ...field.Expr) IUserDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userDo) Having(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userDo) Limit(limit int) IUserDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userDo) Offset(offset int) IUserDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userDo) Unscoped() IUserDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userDo) Create(values ...*models.User) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userDo) CreateInBatches(values []*models.User, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userDo) Save(values ...*models.User) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userDo) First() (*models.User, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.User), nil
	}
}

func (u userDo) Take() (*models.User, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.User), nil
	}
}

func (u userDo) Last() (*models.User, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.User), nil
	}
}

func (u userDo) Find() ([]*models.User, error) {
	result, err := u.DO.Find()
	return result.([]*models.User), err
}

func (u userDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.User, err error) {
	buf := make([]*models.User, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userDo) FindInBatches(result *[]*models.User, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userDo) Attrs(attrs ...field.AssignExpr) IUserDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userDo) Assign(attrs ...field.AssignExpr) IUserDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userDo) Joins(fields ...field.RelationField) IUserDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userDo) Preload(fields ...field.RelationField) IUserDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userDo) FirstOrInit() (*models.User, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.User), nil
	}
}

func (u userDo) FirstOrCreate() (*models.User, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.User), nil
	}
}

func (u userDo) FindByPage(offset int, limit int) (result []*models.User, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userDo) Delete(models ...*models.User) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userDo) withDO(do gen.Dao) *userDo {
	u.DO = *do.(*gen.DO)
	return u
}
